### ISSUE TITLE
Munki thinks network is up when WiFi is on, but not connected

### ISSUE THREAD

**Issue by Steffan-Ravn** [munki/munki#1011]
We are trying to create a Bootstrappr-like setup where we install Munki and some settings from Recovery Mode. We then create the `.com.googlecode.munki.checkandinstallatstartup` and reboot the machine.

The problem is that when Munki is waiting for Network, it is only testing if the returned IP-address is not '127.0.0.1' or '0.0.0.0':
https://github.com/munki/munki/blob/361b18bcc5720658a0b70ed5e2072c62b04c0da6/code/client/managedsoftwareupdate#L125

When we are in the startup-context and Wi-Fi is turned on, but cannot connect to a known network, it will get a self-assigned address (i.e. 169.254.xxx.xxx) which is not a useful network. The check will then determine that network is active, proceed and fail, as we in reality is offline.

You can see this by either running `ifconfig en0` from Recovery Mode or a preflight script when `managedsoftwareupdate` is run. This of course on a laptop where Wi-Fi is en0.

Is it possible to get a more thorough check?

Am I missing something obvious?

**Comment by gregneagle** [comment]
I'm not sure how you get a freshly-built machine to connect to a known WiFi network without user intervention, but assuming you have that problem solved...

Munki's network detection works for the vast majority of cases/orgs/admins, but of course there will always be situations it doesn't handle well. Since I don't have your network, I'm unlikely to be able to directly help you. _I_ don't know how to determine _in your case_ when it is safe to proceed.

The fastest workaround seems to me to be the one suggested to you on Slack: install a preflight script that waits for whatever condition you want before proceeding.

**Comment by Steffan-Ravn** [comment]
> I'm not sure how you get a freshly-built machine to connect to a known WiFi network without user intervention, but assuming you have that problem solved...

We are not trying to connect to a WiFi, I'm simply stating that a freshly built machine has WiFi turned on and as it don't know any networks yet, it will get a self-assigned IP-address (i.e. 169.254.xxx.xxx).

> Munki's network detection works for the vast majority of cases/orgs/admins, but of course there will always be situations it doesn't handle well. Since I don't have your network, I'm unlikely to be able to directly help you. I don't know how to determine in your case when it is safe to proceed.

> The fastest workaround seems to me to be the one suggested to you on Slack: install a preflight script that waits for whatever condition you want before proceeding.

This issue is unrelated to the issue discused on Slack, I simply stumbled upon this situation when troubleshooting. The situation is that upon troubleshooting, I forgot to connect a network-adapter, which means the machine has no network at all, still Munki starts and assumes that there is a network connection, because WiFi has a self assigned IP-address. So it has nothing to do with our network setup. I'm just suggesting that the wait for network will nearly always return true, no matter what, because most machines come with a built in WiFi now. So, to me, that check seems pointless.
But there might be cases I just can't think of or maybe I'm missing something else.

From my understanding, the self assigned address, or APIPA (Automatic Private IP Addressing) is a known and standardized setup, much like 127.0.0.1, and could/should be in the array of excluded or invalid IP-addresses. Unless there is a case where a self assigned address can actually get you to a Munki repository on the network?

The other solution could be, just waiting 60 seconds to see if the Munki-server is reachable. The server is known via the ManagedInstalls.plist-file, so it should be pretty easy to get to. Again - I could be missing something obvious.

**Comment by gregneagle** [comment]
"Unless there is a case where a self assigned address can actually get you to a Munki repository on the network?"

Absolutely there is, and I've made use of it: a completely local network with the Munki repo at munki.local.

"The other solution could be, just waiting 60 seconds to see if the Munki-server is reachable." <-- which is a variation on my suggestion "install a preflight script that waits for whatever condition you want before proceeding."

I'm going to close this issue since there's no clear thing to be done inside the Munki codebase.
