### ISSUE TITLE
new-msc-design: Banner images scale with window and get clipped

### ISSUE THREAD

**Issue by ericholtam** [munki/munki#1029]
Banner images on the main "Software" view scale with the size of the window when resized.  This can cause clipping of the image. 

The previous MSC design does not resize the banner images when resizing the window.

Samples:

Initial launch shows the banner properly:
![clipped_pre](https://user-images.githubusercontent.com/65257798/94469772-46372380-018c-11eb-813e-5abcf64a6bdf.png)

Resizing scales the image with the window size:
![clipped_2](https://user-images.githubusercontent.com/65257798/94469833-5d761100-018c-11eb-9833-fc3585e7c2be.png)
![clipped_3](https://user-images.githubusercontent.com/65257798/94469836-5e0ea780-018c-11eb-8fa2-5a184041c783.png)

**Comment by gregneagle** [comment]
This was actually an intentional change that 1) Looked fine with my test images, 2) more closely matches current App Store behavior, and 3) Allows for bigger/wider images for large displays.

But I'll consider reverting this change and figuring out how to get this behavior in the customized files so people can opt-in.
