### ISSUE TITLE
new-msc-design Big Sur: Progress indicator disappears when app is not frontmost

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#1044]
The progress indicator now uses the native WebKit progress element, and so looks more native on both pre-Big Sur and Big Sur.

But: (and this may be an unfortunate intended behavior in Big Sur) when the app is not frontmost, the progress bar is hidden. Given the obnoxious behavior of the indeterminate progress bar, this might be a good thing when indeterminate, but makes it difficult to monitor the progress of a long, slow download.

Investigate if it's possible to keep the progress bar visible even if the app is not frontmost.

**Comment by gregneagle** [comment]
Additional note: this behavior is the same in Safari in Big Sur.

**Comment by chrisgrande** [comment]
I opened a WebKit bug report about this since it seemed like a regression. I was pointed to testing on 11.3 beta 3, which does appear to fix this bug and the progress element no longer disappears when the window looses focus. (Both MSC and Safari)

https://user-images.githubusercontent.com/825577/110715200-c7cabd00-81d2-11eb-94e2-e8406dd286a7.mov

**Comment by gregneagle** [comment]
Yay. I like bugs getting fixed without me doing anything.

**Comment by gregneagle** [comment]
Closing since recent releases of Big Sur address this.
