### ISSUE TITLE
No progress indication for Adobe CC Packager installers?

### ISSUE THREAD

**Issue by kai-h** [munki/munki#1070]
In starting my testing for rolling out Big Sur and Adobe 2021 apps, I have set up an iMac with a clean install of Big Sur, installed the latest Official Release version of Munki 5.2.1 and imported a bunch of Adobe installers into the repository.
The installers were made via logging in to adminconsole.adobe.com and building the packages there.
Each package is just one app (e.g. just Photoshop 22.1.1 with the Creative Cloud app that you can't exclude).
They were imported into the repository via munkiimport /path/to/Build/Adobe Photoshop 22.1.1_Install.pkg --uninstallpkg /path/to/Build/Adobe Photoshop 22.1.1_Uninstall.pkg

When Munki goes to install them, the Managed Software Centre app says
**Installing Adobe Photoshop 22.1.1:**
Mounting disk image Adobe Photoshop 22.1.1_Install-22.1.1.138.dmg
Starting Adobe Installer...

And then I get the indeterminate progress bar bouncing back and forth until the installer completes.

There's no further progress information in the ManagedSoftwareUpdate.log

The Adobe installer is logging progress information to /Library/Logs/Adobe/Installers/Install.log as expected.

This is purely a cosmetic issue, but it was nice that Munki used to be able to display more detailed progress information than Installer.app.

**Comment by gregneagle** [comment]
Adobe installs have never natively provided progress info. Munki's support for showing progress information has boiled down to:
1) Run the installation process in a thread
2) Figure out where it logs (which has changed over time)
3) Parse the log for messages "of interest" that can help determine progress. These have also changed over time.

It's been a few years since I last looked at this and imagine Adobe has changed yet again #2 and/or #3 above.

I doubt this is something I will spend time on addressing any time soon (or ever), but would welcome someone else who is willing to take a stab.

**Comment by kai-h** [comment]
That's what I guessed Munki was doing - parsing the logs from the Adobe installer and guessing what it was up to.
As I said, it is just a cosmetic issue and not a show-stopper.
