### ISSUE TITLE
Upgrade from Munki 5.6.4 to 5.7.0b3 hangs after python install

### ISSUE THREAD

**Issue by MagerValp** [munki/munki#1136]
We have 5.6.4 deployed to the fleet and imported 5.7.0 b3 with the munkitools5.munki recipe. On our test machines, updating through the GUI hangs after installing the new python package:

```May 11 2022 12:51:24 +0200     The following items will be installed or upgraded:
May 11 2022 12:51:24 +0200         + munkitools_python-3.10.4.4421
May 11 2022 12:51:24 +0200             Embedded Python tools used by Managed Software Center.
May 11 2022 12:51:24 +0200         + munkitools_admin-5.7.0.4422
May 11 2022 12:51:24 +0200             Command-line Managed Software Center admin tools.
May 11 2022 12:51:24 +0200         + munkitools_core-5.7.0.4422
May 11 2022 12:51:24 +0200             Core command-line tools used by Managed Software Center.
May 11 2022 12:51:24 +0200         + munkitools-5.6.0.4411
May 11 2022 12:51:24 +0200             Managed Software Center application.
May 11 2022 12:51:24 +0200         + munkitools_app_usage-5.7.0.4422
May 11 2022 12:51:24 +0200             Application usage statistics for Managed Software Center.
```
...
```
May 11 2022 12:51:39 +0200 Processing installs
May 11 2022 12:51:39 +0200 Installing Managed Software Center embedded python (1 of 5)
May 11 2022 12:51:39 +0200 Installing Managed Software Center embedded python from munkitools_python-3.10.4.4421.pkg
May 11 2022 12:51:41 +0200  Package name is munkitools_python-3.10.4.4421
May 11 2022 12:51:41 +0200  Upgrading at base path /
May 11 2022 12:51:41 +0200     Förbereder installation…
May 11 2022 12:51:41 +0200     Förbereder skivan…
May 11 2022 12:51:41 +0200     Förbereder munkitools_python-3.10.4.4421…
May 11 2022 12:51:41 +0200     Väntar på att andra installationer ska avslutas…
May 11 2022 12:51:41 +0200     Anpassar installationen…
May 11 2022 12:51:42 +0200     3.175 percent complete
May 11 2022 12:51:42 +0200     Kontrollerar paket…
May 11 2022 12:51:42 +0200     22.581352 percent complete
May 11 2022 12:51:42 +0200     Installerar filer…
May 11 2022 12:51:43 +0200     37.106578 percent complete
May 11 2022 12:51:43 +0200     Installerar filer…
May 11 2022 12:51:43 +0200     53.838563 percent complete
May 11 2022 12:51:43 +0200     Tar bort gamla filer…
May 11 2022 12:51:44 +0200     Kontrollerar paket…
May 11 2022 12:51:44 +0200     97.2625 percent complete
May 11 2022 12:51:44 +0200     Registrerar uppdaterade appar…
May 11 2022 12:51:44 +0200     Avslutar installationen…
May 11 2022 12:51:44 +0200     100.0 percent complete
May 11 2022 12:51:44 +0200     Programvaran har installerats.
May 11 2022 12:51:44 +0200  The upgrade was successful.
```
The python install appears to have succeeded, but managedsoftwareupdate seems frozen and doesn't progress to the next install. The three machines where we upgraded through the MSC GUI have all hung, but my iMac where I used --checkonly followed by --installonly on the command line installed without issue.

**Comment by arubdesu** [comment]
We use checkonly/installonly while bootstrapping (with DEPNotify in front, tail'ing the log to provide status) and were noticing a SIMILAR 'hang' symptom under beta 1, here's the traceback when we tried ctrl-c'ing a manual run:

```
^CERROR: Unexpected error in munkilib.installer:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1229, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 1048, in main
    restart_action = doInstallTasks(appleupdatesavailable)
  File "/usr/local/munki/managedsoftwareupdate", line 271, in doInstallTasks
    munki_items_restart_action = installer.run(
  File "/usr/local/munki/munkilib/installer/core.py", line 703, in run
    install_with_info(installdir, installlist,
  File "/usr/local/munki/munkilib/installer/core.py", line 320, in install_with_info
    (retcode, need_to_restart) = handle_apple_package_install(
  File "/usr/local/munki/munkilib/installer/core.py", line 197, in handle_apple_package_install
    (retcode, needtorestart) = pkg.install(itempath, item)
  File "/usr/local/munki/munkilib/installer/pkg.py", line 259, in install
    retcode = _run_installer(cmd, env_vars, packagename)
  File "/usr/local/munki/munkilib/installer/pkg.py", line 178, in _run_installer
    time.sleep(1)
KeyboardInterrupt
    Allowing idle sleep
```

**Comment by gregneagle** [comment]
I guess that makes sense since Munki 5.6.4 ships with Python 3.9, and Munki 5.7 ships with Python 3.10. The installer, while installing the new Python framework, also removes the Versions/3.9 directory, causing the interpreter for the current managedsoftwareupdate run to disappear.
I wonder why we didn't see this the last time we bumped Python versions. 
In fact, I had to write a special cleanup script to get rid of the "abandoned" versions in Python.framework/Versions

**Comment by gregneagle** [comment]
Clever ideas welcome.

**Comment by gregneagle** [comment]
Clever idea #1: change the package identifier for the python pkg to something different, like `com.googlecode.munki.python310`. This should avoid the Apple installer "upgrade" behavior and leave the 3.9 version directory behind until the next managedsoftwareudpate run, which would clean it up. There's some risk there that other things that should be cleaned up won't be.

**Comment by MagerValp** [comment]
I can't come up with anything that isn't a brittle hack, or rearchitecting to make an external binary handle the upgrade. Neither feels particularly palatable.

**Comment by smaddock** [comment]
I think my preference would be for the installer to have it's own Python and use only that. Increases the pkg size but removes the dependency entirely.

**Comment by gregneagle** [comment]
I'm not understanding your comment @smaddock 

Here's the problem:

Munki 5.6.x uses Python 3.9.x. The Python.framework at /usr/local/munki/Python.framework contains a Versions directory, which itself contains a 3.9 directory. The Python interpreter used by Munki 5.6.x uses that interpreter.

When /usr/sbin/installer installs Munki 5.7, which includes a Python.framework with Python 3.10; there is only a Python.framework/Versions/3.10 directory in the package payload, and no Python.framework/Versions/3.9 directory.

Apple installer behavior when installing a new version of a package is to remove any files that were in the perviously-installed version of the package that are not in the version of the package that is being installed. Since the previous version had a Python.framework/Versions/3.9 directory, and the current version does not, Apple's installer removes Python.framework/Versions/3.9

This causes the current managedsoftwareupdate process to hang, as the interpreter it was using (and any associated files) are removed while it's running.

To address this issue, it seems we need to find a way to persist the Python.framework/Versions/3.9 directory at least until the managedsoftwareupdate run completes.

**Comment by gregneagle** [comment]
I've tried experimenting with the `don't-obsolete` property (learn more here: https://macops.ca/flat-packages-persisting-obsolescence/ and here: http://s.sudre.free.fr/Stuff/Ivanhoe/FLAT.html) but that didn't work. My attempt had
```xml
    <dont-obsolete>
        <file path="/usr/local/munki/Python.framework/Versions/3.9"/>
    </dont-obsolete>
```
but perhaps you need to list every single file _inside_ that directory as well :-(

I am a bit confused though. In testing this, I've installed munkitools-5.6.4.4406.pkg on top of Munki 5.7, and doing do leaves Versions/3.10 in place. But if I have a munkitools-5.6.4.4406.pkg install, then install 5.7.0 on top, Versions/3.9 is removed. Apart from one being an upgrade and the other a downgrade, I cannot understand the difference in behavior. And I'm fairly certain we did not see this issue on any of the previous Python version upgrades...

**Comment by gregneagle** [comment]
"if it's just a problem with the managedsoftwareupdate run, have a preinstall script that boots-out the LaunchDaemon and a postinstall script that re-bootstraps it."  Kind of misses the problem: this would kill Munki _during_ the upgrade of its own tools, most likely leaving a partial upgrade in place. And re-bootstrapping it wouldn't cause it to pick up where it left off.

**Comment by smaddock** [comment]
Thanks for the clarifications… I was not fully grasping the munki-installing-munki problem. However, I can still see two ways this could work.

One would be to spawn a separate child process to run `installer`, that is orphaned from the parent munki process. That way the child process can kill/bootout munki proper, execute the install, and reload.

The other is similar but utilizing a temporary LaunchDaemon to run `installer`. So the first stage managed by munki would install the LaunchDaemon and bootstrap it. The second stage managed by the LaunchDaemon would bootout, install, and reload munki.

The second way is essentially the same as apps that utilize a privileged helper tool to download and install app updates in the background, so using a PHT would be a third way. All three work by handing the installation off to a separate process from the app itself.

The issue with all three is they handle munki installs differently than any other installation, except maybe the second because that could be a package wrapped in another package.

To the other point in this issue, I wonder if this is becoming an issue now because it’s the first time a large number of endpoints do not have a system Python to fall back on?

**Comment by gregneagle** [comment]
Shawn: you are proposing non-trivial (perhaps even _huge_) changes to Munki to deal with this issue. It's possible we might have to go down that route. But that would make this a much bigger project, and push the release of 5.7 out weeks if not months or more.

Since no-one has actually asked that Munki's Python get upgraded to 3.10.x, if I cannot find a _simple_ resolution to this issue, it would almost certainly make more sense to consider reverting to Python 3.9.x for now, and move to Python 3.10.x in the future if/when this issue can be addressed.

Some responses to specific points:
Handing off the upgrade of Munki itself to a separate tool is certainly possible, but remember that there are many ways people upgrade Munki, and a common way involves "decomposing" the metapackage into its components. We'd have properly handle every way.
Also: there is no guarantee that an upgrade of the munki tools is the only thing Munki needs to install during an install session. Orchestrating the "regular" Munki installs with the upgrade of the munki tools would require some careful consideration. And you can't just say "if it's a Munki upgrade, do that last" because a macOS upgrade might _also_ be on the list of things to install.

" I wonder if this is becoming an issue now because it’s the first time a large number of endpoints do not have a system Python to fall back on?" very very unlikely since there's no mechanism for a script to "fall back" to other interpreters on disk if the one its using gets deleted.

**Comment by smaddock** [comment]
Understood. Was trying to think of “clever” solutions, but appreciate the feedback on the consequences of what I was proposing. Reverting to Py 3.9 makes sense to me.

**Comment by gregneagle** [comment]
Here's a build of 5.7 with Python 3.9.13: https://www.dropbox.com/s/htlkshosjwbsn6c/munkitools-5.7.0.4423.pkg

@MagerValp and others: can you test to see if this avoids the issue on upgrade from 5.6.4?

**Comment by rrenstrom** [comment]
Here's a potential solution to keep the installer from removing the Python 3.9 framework, by setting a system immutable flag for the files in 3.9 prior to install (this could be done with a preupgrade script in the Python component package), and clear the flag with the package postupgrade script, which will allow the cleanup script to remove 3.9 on the next Munki run.

Tested as follows...

- install just Python 3.9 framework from munkitools-5.6.4.4406.pkg, so it's in place along with existing Python 3.10 from Munki 5.7

```
ls -l /usr/local/munki/Python.framework/Versions/
total 0
drwxr-xr-x  11 root  wheel  352 May 11 09:46 3.10
drwxr-xr-x  11 root  wheel  352 May 19 09:44 3.9
lrwxr-xr-x   1 root  wheel    3 May 19 09:44 Current -> 3.9
```

- count files installed in Versions/3.9 to compare after the following install

```
 find /usr/local/munki/Python.framework/Versions/3.9 | wc -l
    7713
```
- Set system immutable flag for all files in Versions/3.9

```
sudo chflags -R schg /usr/local/munki/Python.framework/Versions/3.9

ls -laO /usr/local/munki/Python.framework/Versions/3.9
total 14856
drwxr-xr-x  11 root  wheel  schg     352 May 19 09:57 .
drwxr-xr-x   5 root  wheel  -        160 May 19 09:57 ..
lrwxr-xr-x   1 root  wheel  -         17 May 19 09:57 Headers -> include/python3.9
-rwxr-xr-x   1 root  wheel  schg 7605552 Apr  6 09:07 Python
drwxr-xr-x   5 root  wheel  schg     160 May 19 09:57 Resources
drwxr-xr-x   3 root  wheel  schg      96 May 19 09:57 _CodeSignature
drwxr-xr-x  19 root  wheel  schg     608 May 19 09:57 bin
drwxr-xr-x   3 root  wheel  schg      96 May 19 09:57 etc
drwxr-xr-x   3 root  wheel  schg      96 May 19 09:57 include
drwxr-xr-x  36 root  wheel  schg    1152 May 19 09:57 lib
drwxr-xr-x   4 root  wheel  schg     128 May 19 09:57 share

```
- install just Python 3.10 framework from munkitools-5.7.0.4422.pkg

- verify no files in 3.9 were removed by installer
```
find /usr/local/munki/Python.framework/Versions/3.9 | wc -l
    7713


ls -l /usr/local/munki/Python.framework/Versions/
total 0
drwxr-xr-x  11 root  wheel  352 May 19 10:06 3.10
drwxr-xr-x  11 root  wheel  352 May 19 09:57 3.9
lrwxr-xr-x   1 root  wheel    4 May 19 10:06 Current -> 3.10
```

- remove the immutable flag for 3.9, so old framework can be removed by cleanup script on next Munki run
```
sudo chflags -R noschg /usr/local/munki/Python.framework/Versions/3.9

```

- run to verify cleanup script removes
```
sudo managedsoftwareupdate
Performing cleanup tasks...
...
Done.

ls -l /usr/local/munki/Python.framework/Versions/
total 0
drwxr-xr-x  11 root  wheel  352 May 19 10:06 3.10
lrwxr-xr-x   1 root  wheel    4 May 19 10:06 Current -> 3.10

```

**Comment by gregneagle** [comment]
Thanks for this idea. I may decide to wait for a future release to try it out, though.

**Comment by MagerValp** [comment]
That's a lovely hack @rrenstrom. Combine it with a cleanup pass on the next munki run and it feels like it could work.

Sticking with 3.9 for the 5.7 release seems like a good idea though, I'll ask my colleague to ditch the old beta and test upgrading to the new one.

**Comment by MagerValp** [comment]
Riffing on the immutable idea: https://gist.github.com/MagerValp/9ea9c8a294ae00ba1cbd56b806195e59

**Comment by MagerValp** [comment]
> Here's a build of 5.7 with Python 3.9.13: https://www.dropbox.com/s/htlkshosjwbsn6c/munkitools-5.7.0.4423.pkg
> @MagerValp and others: can you test to see if this avoids the issue on upgrade from 5.6.4?

No issues upgrading from 5.6.4 to 5.7.0.4423.

**Comment by gregneagle** [comment]
Thanks, all. I'm going to stick with the Python 3.9.13 framework for now so we can get a Munki 5.7 release sooner.

**Comment by erikng** [comment]
Dumb question but why not use "Current" instead of the versioned one?

https://github.com/macadmins/installapplications/blob/main/payload/Library/installapplications/installapplications.py#L1

I'm not sure what ramifications there are, but it would only break (in path terms) when moving to python 4.
