### ISSUE TITLE
Preinstall_alerts not being shown for updated software

### ISSUE THREAD

**Issue by robban247** [munki/munki#1193]
When updating i.e "Super Software" from version 1.0 to version 2.0 the `preinstall_alert` that are set for version 2.0 will not be shown for the end user. This is even when `unattended_install` is set to false.

Lets say by version 2.0 Super Software now requires a license server and the admin wants to inform the user of a required network/VPN connection. This can be non-problematic and problematic in these scenarios:

- Non-problematic: The user has never installed Super Software before and when installing 2.0 they will be shown the `preinstall_alert`
- Problematic: The user has already installed Super Software 1.0 and is not notified about the change in licensing for this software when Super Software 2.0 is pushed to their device. Resulting in the software "for some reason not working", giving some weird error message possibly even misleading the end user and probably ending with a ticket by the end of the day.
 

**Steps to reproduce:**
1. Install one version of a software using MSC
2. Upgrade this software to a newer version where an `preinstall_alert` has been set
3. Notice there are no `preinstall_alert `shown as a part of the update process in MSC. 

**Expected result:**
When the software update is attempted by munki the software should not automatically be installed (even though `unattended_install` is set to true) as there are is a new `preinstall_alert` to be shown to the end user. The end user should instead be notified by a notification (about new updates available) and/or simply seeing the red "new update available" badge on the MSC icon itself in the Dock. 

**Suggestion:**
A possible solution to this might be to have munki check if the `preinstall_alert` has changed at all from the previous version of the same `name`. If there is no change in the text in the alert the end user would have seen the alert for the previous version(s) and should be aware of whatever was mentioned In that alert (one can at least hope - anyway the user has been alerted at one point with the same information). If there however IS a change in the preinstall_alert text from the previous version then one can assume there is new info which the end user really should be alerted about. Also, If there indeed is a change in the alert text I suppose `unattended_install` being set to true should be ignored for that software if the software already is installed.

**Comment by gregneagle** [comment]
`preinstall_alerts` are not triggered for items that are updates (IOW, the item is already installed, and the user is opting into a newer version). For those, you'd use a `predate_alert`. See details on preinstall_alert, pre uninstall_alert, and preupgrade_alert here: https://github.com/munki/munki/wiki/Pkginfo-Files#preinstall_alertpreuninstall_alert

**Comment by gregneagle** [comment]
Note that a preupgrade_alert will only be triggered if the item is installed _but not via optional_install_, and now the user is opting into a keeping it up-to-date. If Munki is just using its normal mechanisms to keep the software updated (IOW, the item is a managed_install (even in the SelfServeManifest) or a managed_update, the preupgrade_alert will not be shown.

For your specific scenario, which appears to be:
1) User installed Super Software 1.0 via optional_installs
2) Super Software 2.0 is available. You want users to upgrade, but also be shown an alert before doing so

Munki does not have a specific mechanism for that. If you absolutely need an alert to be shown, then Super Software 2.0 needs to be a separate item from Super Software 1.0, so that the user must explicitly choose to install it.

**Comment by gregneagle** [comment]
I'm going to close this as "works as designed". If you have a feature request to address a specific scenario, please create a new (feature request) issue describing it clearly.
