### ISSUE TITLE
Question: Does munki have a client CLI tool for software installation and update

### ISSUE THREAD

**Issue by jimcroft** [munki/munki#1200]
Hi folks

I have a question, not an issue. 

I'm working in an org that is using munki and has banned the use other installation mechanisms like homebrew. That org doesn't seem to have an issue packaging up the myriad tools our teams install via brew. So I was wondering if munki had a CLI version of the managed software center for users to list, search, install, update, etc. software.

Thanks

**Comment by arubdesu** [comment]
Hey Mr. Croft, you question is welcome to be posted to the [munki-discuss](https://groups.google.com/group/munki-discuss) list (or the MacAdmins.org Slack's munki channel), but to try to cover what may be the things you're getting at: munki is not a traditional platform-provided package manager, which is what homebrew attempts to emulate. The managedsoftwareupdate cli tool can list the things that are available because they weren't automatically/'silently' installed/updated, and subsequently re-attempt (or force) those installs because the focus of the tool is enabling what admins are responsible to provide to enrolled machines. There is the GUI app for visually making optional installs (and on-demand tasks) available, which do 'under the covers' interact with files that are delivered to the configuration directory used by the tool (with names like manifests and catalogs), but those are not configured to be utilized from the command line directly. So some of the utility you're hoping to proved can be enabled, but not all. Community members have built web portals that allow people to browse the contents of the server-side repo and see the available versions, but there's no direct link I'm aware of to a cli tool.
