### ISSUE TITLE
Partition Map Check - Create OS Pkg

### ISSUE THREAD

**Issue by natewalck** [munki/munki#192]
_From [willpol...@gmail.com](https://code.google.com/u/106269615386648609168/) on September 05, 2012 12:36:57_

Just found out the hard way that Lion doesn't like MBR partition maps. (Who even knew people did that to Macs?)

Anyway, a sanity of partition map type before running the install hooks would be awesome. It would probably only be useful for people like me that doesn't check things before hitting go. :)

_Original issue: http://code.google.com/p/munki/issues/detail?id=192_

**Comment by arubdesu** [comment]
This would belong in https://github.com/munki/createOSXinstallPkg/issues at the very least, but even on googlecode(or perhaps because it was a ghost town over there...) nobody besides the reporter starred it. I recommending closing it? Or, it could be someone's project to add the diskutil check for an mbr partition map to https://github.com/munki/createOSXinstallPkg/blob/master/Resources/installosxpkg_postflight (seems like the right place).
