### ISSUE TITLE
Certificate Bundles - Munki Certificate Issue after changing fro cURL to NSURL

### ISSUE THREAD

**Issue by ltinker** [munki/munki#445]
certificate import process using the ca.pem file needs to import certificate bundles and not just the first certificate in the file. this is was appeared to occur when using cURL

**What steps will reproduce the problem?**
1. requiring client certificate authentication on Munki Server
2. Having a CA Chain in Managed Installs/cert/ca.pem (structure root CA then intermediate CA)
3. running Munkitools 2.1.1.2353 on client machine
4. running managedsoftwareupdate --checkonly

**What is the expected output?**

Managed Software Update Tool
Copyright 2010-2014 The Munki Project
https://github.com/munki/munki

Starting...
    Performing preflight tasks...
    preflight stdout: 
        -- Executing: /usr/local/munki/preflight.d/disableUpdates --
        Disable update check requires run type. Assuming enabled and exiting...

        -- Executing: /usr/local/munki/preflight.d/munkiwebadmin_preflight --
        Preflight report submmitted for mac01.edu.au.
    Completed creation of client keychain at /Library/Managed Installs/Keychains/munki.keychain
Checking for available updates.

**What do you see instead?**

Managed Software Update Tool
Copyright 2010-2014 The Munki Project
https://github.com/munki/munki

Starting...
    Performing preflight tasks...
    preflight stdout: 
        -- Executing: /usr/local/munki/preflight.d/disableUpdates --
        Disable update check requires run type. Assuming enabled and exiting...

        -- Executing: /usr/local/munki/preflight.d/munkiwebadmin_preflight --
        Preflight report submmitted for mac01.edu.au.
    Completed creation of client keychain at /Library/Managed Installs/Keychains/munki.keychain
Checking for available updates...
2015-01-21 12:31:18.943 Python[49605:2b23] CFNetwork SSLHandshake failed (-9831)
2015-01-21 12:31:18.944 Python[49605:2b23] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9831)
ERROR: Could not retrieve manifest mac01 from the server: Error -1205: The server “munkiprod.edu.au” did not accept the certificate.
ERROR: Could not retrieve managed install primary manifest.

**What version of the Munki tools/InstallOSpkg tools are you using? On what
version of OS X?** running OS X 10.9.5 with Munkitools 2.1.1.2353 

**Please provide any additional information below.**

from what i can see,
our ca.pem which contained the root CA then the intermediate CA (intermediate CA is used to sign the client certificate) only the first certificate is imported into the keychain when running managedsoftwareupdates, in this case the intermediate CA was never imported, as a result the clients certificate is untrusted.

i was able to validate this by adjusting the ca.pem file to only include the intermediate CA, when running managedsoftwareupdate the certificate was imported but due to it not being trusted it still failed with the error 
"ERROR: Could not add CA cert /Library/Managed Installs/certs/ca.pem into System keychain: 1: SecTrustSettingsSetTrustSettings: One or more parameters passed to a function were not valid."

checking the key chain i could see the intermediate CA was now in the keychain

I then changed back to having the ca.pem file with the Root CA then the intermediate CA,
running managedsoftwareupdate then updated as expected as the keychain was now able to associate the client certificate with the intermediate which was associated with the root CA.

**Comment by gregneagle** [comment]
It's not clear if `security add-trusted-cert` even supports importing certificate bundles.

You might need to just import these certs (and trust them) into the System.keychain via some other method, or split these into separate files and put them in a cert directory pointed to by Munki's SoftwareRepoCAPath preference.

I don't have a similar setup with which to test any of this; I can only offer advice.

**Comment by pudquick** [comment]
```
ERROR: Could not retrieve manifest mac01 from the server: Error -1205: The server “munkiprod.edu.au” did not accept the certificate.
```

This says that the client successfully contacted the server but that the server rejected the provided client certificate.

munki attempts to configure a identity preference for the munki repo URL. The error message is indicating that either: the wrong identity preference was used (maybe multiple are configured?) or the client certificate itself on the workstation does not meet the security requirements in the configuration of the munki repo webserver.

For diagnostics, I'd grab the munki.keychain file from /var/root/Library/Keychains/munki.keychain and copy it to a normal OS X user home directory on the workstation. Then I'd log in as that user on the workstation, open Keychain Access, open the copied munki.keychain.

Then I'd try to visit https://munkiprod.edu.au   from Safari. munki now uses the same security mechanisms that Safari itself uses, so its keychain/SSL trust/certificate parsing/etc. is virtually identical. If Safari can visit the URL, then munki should generally be able to.

If you get a prompt telling you to select an identity preference, then the issue is that you have more than one configured - look for an identity preference item in the System.keychain

If you get a prompt saying that you weren't allowed to talk to the server, you need to look at your client certificate and verify it against your security configuration for HTTPS on your webserver as apparently it's not configured to trust the client certificate on the munki client machine.

**Comment by ltinker** [comment]
Thanks for looking at this guys,

I had managed to fix/workaround this problem before reporting it by writing a separate script to import the certificates from the CA bundle one at a time into the keychain thus reestablishing the CA Chain for validating the client certificate.

I thought id report it as i noticed it was not an issue when Munki was using cURL for this function.

**Comment by gregneagle** [comment]
The hope was the move to NSURLConnection and the OS X keychain would be (mostly) pain-free for people, but there are so many potential variables that it's inevitable that there will be configurations that worked with Munki 2.0.x that don't work without tweaking in Munki 2.1+. 

I'd be happy to look at this issue further if I had access to resources that allowed me to replicate it.

In any case, if you have a usable workaround, that's great.

**Comment by ltinker** [comment]
I expected to run into some issue somewhere, I mean I'm actually migrating from munkitools 0​.9​.2​.1846​.0
I am hoping to have a look at it further my self, i sort of expected the majority of Munki deployments do not use a certificate bundles.
