### ISSUE TITLE
munkiimport Unicode bug

### ISSUE THREAD

**Issue by diwanicki** [munki/munki#456]
munkiimport version 2.2.2.2414; OS X 10.10.3 (14D87h)

Attempted to import Logitech Unifying Software.mpkg (from http://www.logitech.com/pub/controldevices/unifying/unifying1.10.421.dmg)

get the following error:

    munkiimport /Volumes/Logitech®\ Unifying\ Software/Logitech\ Unifying\ Software.mpkg 
    /usr/local/munki/munkiimport:838: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
      arguments.remove(installer_item)
    Traceback (most recent call last):
      File "/usr/local/munki/munkiimport", line 1104, in <module>
        main()
      File "/usr/local/munki/munkiimport", line 838, in main
        arguments.remove(installer_item)
    ValueError: list.remove(x): x not in list

**Comment by diwanicki** [comment]
Moving the .mpkg to Desktop allows for expected import behavior

**Comment by gregneagle** [comment]
Thanks for filing this; something quite similar was mentioned recently but I don't think an actual issue was opened.

If you test, you'll probably see that `makepkginfo` has no trouble parsing the file, even with Unicode characters in the pathname.

This issue is triggered when `munkiimport` calls `makepkginfo`; paths with Unicode characters don't seem to make the round-trip unscathed -- when the pathname comes back from `makepkginfo` it no longer matches the path as it was stored before being sent to `makepkginfo`. I played with it a bit and made no progress, but now that this issue has been created it will stay on my radar.

**Comment by gregneagle** [comment]
Another data point: If you download the disk image referenced above and do a munkiimport against the disk image itself, the problem does not occur:

```munkiimport ~/Downloads/unifying1.10.421.dmg ```

**Comment by gregneagle** [comment]
This should address the issue: https://github.com/munki/munki/commit/ba387f2b7ce36a31504548f3ae84d22fd67f4496
