### ISSUE TITLE
munkiimport use as existing template - copy Display Name

### ISSUE THREAD

**Issue by erikng** [munki/munki#483]
It would be nice if munkiimport would also copy the Display Name when importing an updated package. I think in most cases, the Display Name is going to be the same.

**Comment by gregneagle** [comment]
Many packages used to have their own display name, and so makepkginfo attempts to extract that. By the time it gets passed back to munkiimport, munkiimport doesn't know if this is an actual new display name extracted from the package itself, or the ugly default.

With the transition to flat packages, fewer pkgs actually have a display name within, as that appears to be supported only with distribution-style flat pkgs (those built with productbuild) and not component packages (those built with pkgbuild).

There are lots of UI issues caused by this sort of thing, and no easy solutions.

**Comment by erikng** [comment]
All those issues aside, why can't munkiimport pull the Display Name from a previous pkginfo?

If you hit "y", it should be expected that you don't care about the new Display Name anyway.

**Comment by gregneagle** [comment]
It could. It doesn't currently.

**Comment by aysiu** [comment]
I'm not sure what other people would prefer. I would like munkiimport, if I decide to use the old template, to keep that template's display name. Right now, it appears to be preferring the display name from the .pkg info:
https://github.com/munki/munki/blob/master/code/client/munkiimport#L970-L972

Could munkiimport prefer it the other way around and keep the template Display Name?
