### ISSUE TITLE
Warning: Cannot efficiently manage Apple Software updates

### ISSUE THREAD

**Issue by mkuron** [munki/munki#511]
Since upgrading my clients to Munki 2.3.0, I see the following warning on all clients in MunkiWebAdmin:
> Cannot efficiently manage Apple Software updates because softwareupdate's CatalogURL is managed via MCX or profiles. You may see unexpected or undesirable results.

My clients get a _CatalogURL_ in _com.apple.SoftwareUpdate_ via MCX so that the regular Apple software update mechanism also goes to our Reposado server. The message suggests using a _SoftwareUpdateServerURL_ in _ManagedInstalls_ instead, which would not point Apple software update to the Reposado server.

The message comes from 9e0deb754083c671f8005f05e7ec44fbe001b790. In the code, it looks like there is no way to make the warning disappear on both OS X 10.10 and lower and OS X 10.11 and higher with the same configuration. The former requires _SoftwareUpdateServerURL_, the latter _CatalogURL_. Obviously, it would be desirable to apply the same settings to all clients irrespective of their OS version.

What do these "unexpected or undesirable results" consist of? As far as I can tell, everything has been working just fine for me and I would appreciate some way of getting rid of the warning.

**Comment by jessepeterson** [comment]
Munki depends on overriding the CatalogURL for it's normal function of serving Apple updates. When *CatalogURL* in *com.apple.SoftwareUpdate* is managed via MCX/Profiles (and not merely set in the preference files) then Munki cannot override it. This is because, I believe, `softwareupdate` strictly pays attention to the MCX keys and not Munki's override of the CatalogURL.

This manifests itself if *SoftwareUpdateServerURL* in *ManagedInstalls* is different than *CatalogURL* in *com.apple.SoftwareUpdate* or when Munki does it's local caching and serving of software update catalogs. There might be other problems, too, but that's what jumps to mind. This problem in particular:

https://groups.google.com/forum/#!topic/munki-dev/fxnOkoweSIo

**Comment by gregneagle** [comment]
You can "get rid" of the warning by not using MCX or configuration profiles to manage com.apple.SoftwareUpdate's CatalogURL. Instead, use `defaults` or some other method to set the CatalogURL in /Library/Preferences/com.apple.SoftwareUpdate.plist.

As for not being able to have a single configuration that works for both 10.10 and lower and 10.11 and higher, there is not much that can be done about that. Apple continues to change how softwareupdate behaves from release to release and we must change what we do as well.

If you want a single configuration that works on all supported OSes, do not define Munki's SoftwareUpdateServerURL preference, and configure com.apple.SoftwareUpdate's CatalogURL via `defaults`.

**Comment by gregneagle** [comment]
jessepeterson wrote: "Munki depends on overriding the CatalogURL for it's normal function of serving Apple updates. "

It does under 10.10.x and earlier. The main reason is because in softwareupdate in 10.10.x and earlier, calling softwareupdate -i to install (even previously downloaded) updates causes an entire update check to happen, which requires getting the current sucatalog, which requires connectivity to the softwareupdate server if the sucatalog is fetched via http/https.

This presents a number of problems:

First, it slows down the install run, since we have to do the (slow, expensive) check again. 

Second, it's possible that NEW items could be downloaded, making a `softwareupdate -i -a` run possibly install additional things we did not know about when we started the run. It's possible some of these new items might require a restart; and perhaps when we started the run we had no items that required a restart, so now we might be in a bad state: we're installing items while the user is logged in and then we get to tell the user he/she needs to restart immediately. Poor user experience.

Third: if the softwareupdate server is not available for any reason (the previously linked to 802.1X issue; downloads happened while connected to the corp network and the SUS is available only on the corp network, but now the machine is at the user's home, etc) the install will fail -- even though we have the needed packages already downloaded.

So to prevent these issues, we steal a page from reposado and replicate all the needed SUS resources locally, then set the CatalogURL to point to a local file:// resource. This allows softwareupdate to work even if we can't reach the (original) SUS, and prevents discovery and download of additional updates, since the local file:// .sucatalog contains _only_ the current applicable updates. It's fiendishly clever, if I do say so myself.

Enter 10.11.

In 10.11, softwareupdate refuses to use a file:// CatalogURL. So we can't do any of our cleverness. But there is a new feature that mitigates some (all?) of the same issues:  softwareupdate in 10.11 supports a new `--no-scan` flag that can be added to `softwareupdate -i <someupdate>`. This appears to suppress the update scan and proceeds directly to installing the previously downloaded updates.

So in 10.11, we can't use file:// sucatalogs to prevent softwareupdate from needing to talk to the update server at install time, but it appears we can use the --no-scan flag to similar effect.

That leaves the CatalogURL vs SoftwareUpdateServerURL. I missed this in the past, so I'm not 100% sure when Apple started this, but I suspect it was the same time as the undocumented `-CatalogURL` option went away and the new `--set-catalog` option was added, so that places it with the introduction of 10.9: softwareupdate does much more local caching. This caching level seems to have been raised in 10.11. Switching the CatalogURL causes Apple's softwareupdate cache to be invalidated. In 10.9 and 10.10 this appeared to have no ill effects (other than probably slowing down the scan process as it could no longer use cached results), but in 10.11, switching the CatalogURL seems to confuse softwareupdate in some scenarios. I don't have any notes handy so I can't provide specifics, but I saw odd behavior that went away when I removed the SoftwareUpdateServerURL preference and instead allowed softwareupdate to just use the system-defined CatalogURL.

I'm more than happy to have others put eyes on this; there's only so much testing I can do and have time to do, so it's entirely likely I've missed important details.

But it looks like the correct approach under 10.11 is to minimize the fancy stuff Munki tries to do and instead use the tool as much as possible as Apple expects us to.

**Comment by mkuron** [comment]
Thanks for all the details. I've thought about this a bit myself and looked for alternative solutions, but it seems like you got everything covered. Two comments:
- It would be good if we had some way to replicate the `--no-scan` behavior on 10.10 and earlier. Then Munki could use the 10.11-style _CatalogURL_ method if a _CatalogURL_ was set, and use the _SoftwareUpdateServerURL_ method if not.
I found that `softwareupdate -i -a` does not always perform a scan, so I'm pretty sure there must be some way to reproducibly prevent scanning (e.g. by setting a last-scan timestamp in some plist or setting the last-modified timestamp on some file). I'll let you know if I find it. Of course, this would be a bad hack, but then again all of the Munki Apple Software Update integration is a hack.
- The _file://_ URL issue in 10.11 could easily be bypassed if Munki served a HTTP server itself, e.g. using _SimpleHTTPServer_ from the Python standard library. Assuming `--no-scan` does make all of the Munki cleverness unnecessary, of course we don't need it. But if there is anything `--no-scan` prevents Munki from doing, that might be worth a thought.

**Comment by gregneagle** [comment]
"It would be good if we had some way to replicate the --no-scan behavior on 10.10 and earlier. "

I never found one; thus all my cleverness around file:// URLs. If you are seeing `softwareupdate -i -a` not always scan, I suspect that's new starting in 10.9 and related to the new internal caching. I'm not likely to replace one hack for another for older versions of OS X unless we can prove it's really superior.

"The file:// URL issue in 10.11 could easily be bypassed if Munki served a HTTP server itself, e.g. using SimpleHTTPServer from the Python standard library."  

For some definition of "easily". I thought about this, but there is the matter of making sure you don't bring up the server on a port that is already in use. (Which might not be that hard -- I really haven't investigated what would be needed.) And if you do pick a random unused port, you need to hope that some other software installed doesn't expect to use it at will while your SimpleHTTPServer is running. I'm hopeful the `--no-scan` flag will make doing this unneeded.

**Comment by ccaviness** [comment]
FYI, if you request port 0, the system will assign you an ephemeral high-number port.

**Comment by gregneagle** [comment]
Thanks, Clay. I really hope _not_ to be implementing an internal http SUS server using SimpleHTTPServer in Munki.

**Comment by gregneagle** [comment]
Closing this is it's not actually an issue and no action needs to be taken.
