### ISSUE TITLE
Munki should show managed installs consistently

### ISSUE THREAD

**Issue by camillol** [munki/munki#529]
Right now, Munki is inconsistent about showing managed (non-optional) installs. For example, today an update was triggered on my machine, and Munki showed 4 available updates: it had a red badge on the app icon, and they showed up with icons, names and description in the Update tab. However, they later disappeared from the Update tab, and now they do not show up in My Items, or in Software, or in Search. But I know they're there.

I think this inconsistency should be resolved in the direction of always making the managed installs visible; at the very least, they should show up when searching inside Munki.

For another example, "git" used to be an optional install at my company. Then it was made a managed install, which made it disappear from Munki. Some time ago I wanted to update my git, and it took some time to figure out where it had come from. I suspected Munki, but when I searched for it, it said "no results". It took some time to figure out it was in fact installed by Munki.

**Comment by gregneagle** [comment]
While I'm not 100% sure I follow what you are seeing/describing, this sounds more like a discussion for the munki-dev or munki-discuss lists.

Managed Software Center displays two types of things: updates managed by the administrator, and "Optional Installs": items that can be installed or removed by the end user.

Updates managed by the administrator only appear when they are pending: the end-user can then decide to install them now, or wait until later.

Software that is managed by the administrator, but has no pending updates, does not appear in the Managed Software Center interface because there is nothing meaningful the user can _do_ with these items -- they are controlled by the admin.

This is similar to the App Store: it shows items you can install from the App Store, and updates managed by Apple. Those Apple updates show up only when they are pending -- you can't look at them in the App Store interface after they've been installed.

You might not like this design decision. If you think others might agree with you, start a discussion on munki-discuss. But here I would just say "behaves as designed"...

**Comment by camillol** [comment]
The App Store updates that have the behavior you are referencing are updates to the base system and the software included with it. They show up in the App Store because Apple decided to fold Software Update into it to drive adoption. In any case, there is no question of where they come from, and they are always provided in the same way. Nobody is going to look at /System/Library/CoreServices/Finder.app and wonder where it came from and why it does not show up in the App Store.

The situation is completely different with Munki. You get apps that show up on some Macs and not others, depending on what the admins decided. And the set of managed apps can and does change over time, with no warning. Suddenly an app shows up and you have no idea where it came from. Being able to verify that in Munki is the meaningful action that I want to be able to do as a user.

**Comment by gregneagle** [comment]
I did suggest you start a discussion in public on the munki-discuss list. You can still do that at any time.

**Comment by erikng** [comment]
Items can appear and disappear if they are set to install unattended. If someone has an application open, munki will intelligently display this update to the user. If they exit out, on the next run munki will silently update. 

I like this behavior and imagine many others do as well. I would be highly against changing this behavior.

If you always want updates to be user visible (not sure why you would), don't use unattended installations.
