### ISSUE TITLE
Bootstrap not working on 10.11

### ISSUE THREAD

**Issue by xEnt22** [munki/munki#542]
I have a deploy studio setup and script that will bootstrap into munki using a fresh 10.10 untouched image when it gets to the first screen. however when i swap that 10.10 image around with a 10.11 untouched one, it does not bootstrap. using exact same configuration. 

This is using the latest munki, will post logs soon

**Comment by gregneagle** [comment]
Many people including myself, are successfully bootstrapping Munki on 10.11, so I'm reasonably certain your issue lies outside of Munki; perhaps with DeployStudio or its workflows.

I recommend just using a _package_ to install the required bootstrap file. One can be found here: https://dl.dropboxusercontent.com/u/8119814/munki_kickstart.pkg

**Comment by xEnt22** [comment]
Thanks ill try that and see how it goes.
