### ISSUE TITLE
Logout and update not showing progress bar

### ISSUE THREAD

**Issue by SillySalamander** [munki/munki#582]
For some reason the progress bar does not show when an update is set to "logout and update." We are on el capitan and are using certificates for the repo. The feature used to work fine before.

**Comment by gregneagle** [comment]
Before what? Before El Capitan?

Do you have a Policy Banner? In El Capitan, the Policy Banner gets displayed in front of the MunkiStatus window.

We don't use the Policy Banner, so I never noticed/wasn't motivated to do anything about it. But some work recently has been done to address that in the policy-banner branch: https://github.com/munki/munki/commits/policy-banner

**Comment by SillySalamander** [comment]
It would have to be either before el capitan or before certs we did both pretty close together. We do not use a policy banner

**Comment by gregneagle** [comment]
I would suggest posting on munki-discuss: the status window displays as expected here on El Capitan, and I've seen no other reports of it not displaying.

**Comment by SillySalamander** [comment]
theres no chance that this occurs because the system cannot access the cert for the munki repo because no user is logged in?

**Comment by SillySalamander** [comment]
if I try to call munki and am not logged in as a local user then the update check fails with "this repo requires a client certificate"

**Comment by gregneagle** [comment]
Definitely post on munki-discuss. You have a problem with how you have configured client certificates, not a code issue with Munki. Properly configured, the client cert should be available even when no-one is logged in.

(it was not clear from your original post that managedsoftwareupdate was failing at the loginwindow -- you mentioned only that the progress bar wasn't showing)

**Comment by SillySalamander** [comment]
sounds good thanks for all that you do

**Comment by atoss** [comment]
So, even though the originally poster turned out to have a different issue, I'm having the exact issue that was originally described.  My clients have suddenly stopped showing a progress bar at the login window.  I can't figure out what's wrong.  The last time that a restarting-required update was deployed, the users saw the progress bar at the login window.  However, for this most recent Apple Security update, users are not getting the process bar.

In my case, everything is still working, managedsoftwareupdate runs from the login window in the background and will actually restart the computer when installs are complete, but there's no visual indication that anything is happening.  If a user _does_ log back during updates, you can actually watch the progress from he Managed Software Update app.  It's just very confusing for the users because they're prompted to logout and when they do, it doesn't look like anything happens.

What do you think might have changed in my munki setup?  Any ideas on how I can get the progress bar working again?

Thanks.

**Comment by gregneagle** [comment]
Please either open a new issue with more details, or (preferably) start a conversation on the munki-discuss mailing list. I'd like the issues tracker to track actual reproducible issues (which this might turn out to be), and not be a general support mechanism/discussion forum.

**Comment by SillySalamander** [comment]
Just to clear the air, we renamed the managed software update app to make it less of a mouthful. Everything worked fine until we later discovered that the progress bar would not show when logging out and updating. This update coincided with our el capitan update, hence the confusion.

**Comment by atoss** [comment]
I will post a new issue, thank you for responding.  Also, I'm glad that SillySalamander replied also.  It's worth noting that our Managed Software Update app has also been renamed.  Though we've done that since we started using Munki last year (when the progress bar worked properly), so I didn't think it was relevant.  But it's worth noting that the app was also renamed for us on our clients.

**Comment by gregneagle** [comment]
@SillySalamander -- Yes: renaming the app would break this:

https://github.com/munki/munki/blob/master/launchd/LaunchAgents/com.googlecode.munki.MunkiStatus.plist#L13

and this:

https://github.com/munki/munki/blob/master/launchd/LaunchAgents/com.googlecode.munki.ManagedSoftwareCenter.plist#L15

You could probably rename the app and also update those LaunchAgents and be OK... but don't be shocked when I personally don't spend a lot of time troubleshooting issues around this.

**Comment by gregneagle** [comment]
@atoss Renaming the app is almost certainly the cause of your issues as well. The LaunchAgents can no longer find Managed Software Center.app or MunkiStatus.app.

**Comment by SillySalamander** [comment]
OK, this is not exactly mentioned very prominently. I would keep this post up and mark as resolved to keep others from asking the same question.

**Comment by atoss** [comment]
Well, that answers that.  Don't know why it never occurred to me that might be a factor.  But it's strange that it used to work, isn't it?  I won't create a new issue for it.  Thanks for pointing me in the direction to fix this.  I wouldn't want you to waste any effort on things like this.  But much appreciated for pointing me in the right direction.  I'm still learning the ins and outs of how Munki works, so it's not surprising that I missed something like this.

As previously stated, THANKS FOR ALL YOU DO!!!

**Comment by gregneagle** [comment]
"OK, this is not exactly mentioned very prominently." It's not mentioned at all because it's not something I'd thought people would do. (And not something I would do for obvious reasons)

**Comment by SillySalamander** [comment]
People do stupid stuff :) And have users that complain and complain about Managed Software Center being too long of a name

**Comment by schwifty** [comment]
I think you mean “stupid stuff, like complaining about Managed Software Center being too long of a name.” This is the first time this has come up in five years of doing this.

Make an alias for them.

**Comment by atoss** [comment]
Just to follow up on that last comment...

When I change anything like this, I do it with full responsibility, knowing that I'm working outside of expected behavior.  So, I'm in full agreement with you that it's not something you should spend effort on.

On the flip side, it's worth noting why some organizations would choose to change the name of the app.  We did it at our school because we wanted our users to feel less confused when they see this strange  App store on their Macs.  We named ours "<nameofourschool> App Store."  Which gives them comfort in distinguishing between Apple's Mac App Store and ours used for software deployment.  It's subtle, but effective.  We could have gotten away with keeping "Managed Software Center," but ultimately decided that users would have a better sense of where to find school-deployed software by labeling thusly.  I don't think it's got anything to do with being too long of a name, it's more about branding for us.

As I said, I wouldn't spend any additional effort on this for now.  But it may not hurt to keep in the back of your mind that some users may want to "re-brand" the app as we did... just in case anyone else has a similar issue down the road.

Thanks again!

**Comment by gregneagle** [comment]
But renaming it in the Finder doesn't change the display name in the app itself.

Better to leave the filename alone and do something like this:

https://github.com/ox-it/munki-rebrand/

**Comment by gregneagle** [comment]
And if you are troubleshooting an issue -- and you have modified the install -- you should always test to see if the issue exists on an unmodified install. "just in case anyone else has a similar issue down the road."

**Comment by atoss** [comment]
On the second point, you're absolutely right.  Normally, I'd use a "vanilla" config to test issues.  Normally my first line of troubleshooting is to look out on the interweb machine and see if anyone else is having the same problem.  Which led me to this post in the first place.  Though, I jumped the gun in joining the conversation without having fully troubleshot the issue.  Fortunately, it worked out for me, since you were able to provide me with great info about what I was doing wrong.

Speaking now to your first point, you're right that changing the name in the finder doesn't change the name of the app itself.  I'd initially considered how much I wanted to "re-brand" the app, but decided that a simple file rename was sufficient, since that's all that's needed for users to find the app in their spotlight searches.  It was an attempt to be as least invasive as possible.  

That said, thank you for sharing the Oxford info.  That could be really useful if we wanted to completely overhaul the branding of the App.  I likely won't spend that kind of effort on it in the near term.  I'll probably just alter the launchagents as part of the install.  That should do the trick.

Thanks!  FYI, adopting Munki at our school last year was one of the biggest leaps forward for managing our Macs.  Keep up the great work!

**Comment by SillySalamander** [comment]
I think its fair to say that if you can customize literally anything about the app -- which is prominently displayed in the documentation, its logical to assume that people would change the name of the app as well.

**Comment by gregneagle** [comment]
The only _supported_ customizations are the ones that are documented.

**Comment by erikng** [comment]
Little late to the party here but I don't understand the need to change the name. 

Our users (in education mind you) quickly understood what the app name was. We put it on the dock, remove the App Store icon and I have a push notification upon first login to read documentation on MSC.

Good documentation / processes trump a need to rename the application. Do you rename Safari to Internet Explorer?

**Comment by atoss** [comment]
I have to say, I'm a little surprised by the latent hostility surrounding this topic.  Frankly, I never thought that original poster made particularly good arguments for his case and have fully sided Greg's position from the beginning.  I even thanked him for helping resolve our specific issue while recognizing that it was above and beyond what was necessary from him as a developer, as it was I who was working outside of supported use of the software.

That said, it's not really for _you_ or anyone else to understand why our organization made the decision to alter the name of the app.  It's something _we_ determined would better for _our_ users, not yours.  True, good documentation and processes are essential, but renaming the application was a method we used to _compliment_ those processes (good luck getting _all_ your users to read that documentation of yours).  

And, no Mr. Smartypants, we don't rename Safari to Internet Explorer because not only are those apps two very well-known internet browsers, but our users are also savvy enough to understand which platform they're using in the first place (did _you_ know that Internet Explorer is not available on the Mac?).  What they're _not_ familiar with is an obscure application that they'd never heard of before with such a generic name as "Managed Software Center."  NOT that it's a bad name for most organizations, but _our_ users appreciated the extra "branding" of the app which, as it happens, also match a series of other in-house apps deployed for our users that have similar naming schemes.  Your Safari / IE analogy was really quite a terrible one as it was more like comparing apples to donuts.  (Just to clarify, those are very different from each other, yet they're both food.)

So, your comment about how _you_ don't understand someone else's methods of which _you_ know nothing about really contributed _nothing_ to this _closed_ conversation.  Greg's final statement was a PERFECT statement on which to end this discussion.  (Thanks for ruining it.)

Personally, I wouldn't have even acknowledged such an ignorant line of questioning, but it's Sunday morning and I have some time to kill while enjoy my morning coffee.  However, if anyone does feel compelled to reply to this, don't expect any further responses from me.  I'll be riding my high horse back to work.
