### ISSUE TITLE
Branding issue munki 2.7.0

### ISSUE THREAD

**Issue by islamadel** [munki/munki#611]
Hello, I used to modify the standard Branding pictures of munkitools in versions prior to 2.7.0 in showcase_template.html by changing this line
`<img href="#" alt="Branding" src="static/branding.png" />`
and entering a remote image on my server for the src tag.
since I upgraded to munkitools 2.7.0, the remote images don't work at all.
Is there a reason why it isn't working anymore or how can I make it work?
Thanks

**Comment by gregneagle** [comment]
Could you provide an example customized showcase_template.html that behaves as desired in Munki 2.6.x and does not in Munki 2.7.0? For your "remote images", if your web server is not external accessible, substitute any publicly-hosted images.

**Comment by gregneagle** [comment]
If MSC.app is built under 10.11 with the latest MacOS SDK, it's likely that App Transport Security (ATS) is getting involved. 

See the section on App Transport Security here:
https://developer.apple.com/library/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html

See Since MSC.app "normally/usually" uses internal file:// URLs, ATS doesn't really have an effect. But with "external" (http/https) URLs, it's likely that ATS is blocking the connection(s).

You can test if this is the issue by adding the following key and value to Managed Software Center.app/Contents/Info.plist:

```xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

See also https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33 (under NSAppTransportSecurity)

**Comment by gregneagle** [comment]
Added this to MSC.app's Info.plist here:
https://github.com/munki/munki/commit/bd068281db6c84d414420f0aa103917ade7562d4

**Comment by pnerum** [comment]
I can confirm we have the same issue. Not only with sidebar_template.html, but also with  screenshots in product description.

This is a part of the plist file that does work with MSC 2.6.x and doesn't with 2.7.0.
In the Info.plist (MSC 2.7.0) I don't have a NSAppTransportSecurity entry.

```xml
	<key>description</key>
	<string>AutoCAD is a computer-aided design (CAD) program used for 2-D and 3-D design and drafting.
&lt;br&gt;
&lt;br&gt;
&lt;span id="imgSlider"&gt;
&lt;img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Willem_de_Kooning_(1968).jpg/220px-Willem_de_Kooning_(1968).jpg" id="productImageSmall" onclick="dim(true,this);"&gt;
&lt;img src="http://munki.wdkaitlab.local/artwork/autocad/autocad2.jpg" id="productImageSmall" onclick="dim(true,this);"&gt;
&lt;img src="http://munki.wdkaitlab.local/artwork/autocad/autocad3.jpg" id="productImageSmall" onclick="dim(true,this);"&gt;
&lt;img src="http://munki.wdkaitlab.local/artwork/autocad/autocad4.jpg" id="productImageSmall" onclick="dim(true,this);"&gt;
&lt;/span&gt;
&lt;br&gt;
&lt;h1&gt;CAD tools for design and documentation&lt;/h1&gt;&lt;br&gt;
See how intelligent tools in AutoCAD® design and documentation software help speed up your work, and how CAD features add precision to your drawings. View designs more clearly with Stunning Visual Experience and document in context with Coordination Model.  
&lt;br&gt;
&lt;br&gt;
&lt;h1&gt;Document with confidence&lt;/h1&gt;
Create stunning designs and speed up documentation work with productivity tools in AutoCAD® software.
&lt;br&gt;
&lt;ul&gt;
    &lt;li&gt;Share your work with TrustedDWG™ technology&lt;/li&gt;
    &lt;li&gt;Work across integrated desktop, cloud, and mobile solutions&lt;/li&gt;
&lt;/ul&gt;
&lt;br&gt;
&lt;br&gt;
&lt;span id="player"&gt;23z30uz4UBo&lt;/span&gt;</string>```

**Comment by pnerum** [comment]
I can confirm the MSC 2759 version resolves the issue.

**Comment by gregneagle** [comment]
Thanks for confirming.
