### ISSUE TITLE
Make a System.keychain client certificate usable for managedsoftwareupdate

### ISSUE THREAD

**Issue by FreshXOpenSource** [munki/munki#662]
We use a SCEP system via a mobileconfig profile to enroll client-certificates to our devices automatically (namely micromdm/scep). The mobileconfig profile gives us a lot of advantages over a manual cert+key rollout which we would like to keep. In this provision process our device gets a client-certificate +key enrolled into the system keychain. Currently munki only allows to run with certificate+keyfiles on disk and does not send a client certificate encrypted request otherwise.

It would be very handy if gurl.py would be able to handle also certificates from the System.keychain if it gets to know which certificate id to use via ManagedInstalls.plist or a command line flag

**Comment by gregneagle** [comment]
This should work right now if you properly configure an identity in the System.keychain.

The trick is "properly configure".

**Comment by gregneagle** [comment]
"Currently munki only allows to run with certificate+keyfiles on disk"

This is actually _not_ the case. Munki will happily construct a local keychain file from certificate+keyfiles on disk if provided, but if System.keychain is pre-configured with the needed certs and identity preferences, Munki (actually NSURLConnection/NSURLSession) will work with those.

**Comment by gregneagle** [comment]
Your major task would be to set the proper identity preference in the System keychain.

**Comment by FreshXOpenSource** [comment]
Ok, how does a proper configuration a.) in the keychain b.) in the munki settings looks like.
Is this documented? The Munki Preferences docu did not reveal anything.

**Comment by gregneagle** [comment]
There currently is no documentation on this. Perhaps you can write it.

General overview:
Server CA cert and client cert and key and Identity preference linking the client identity (cert+key) to your Munki server's URL must be in a keychain in Munki's keychain search path.

This keychain _could_ be the System keychain.

The code in Munki dynamically creates a munki.keychain and inserts it into the keychain search path.

But in theory you could insert all this same data into the System.keychain -- though I'm not sure how difficult it is to insert an identity preference into the System.keychain. If that's not possible, you might be out of luck and there would be nothing Munki could do about that -- we're just using Apple/macOS capabilities here.

The complexity around this is one major reason we elected to do things the way they are currently -- this also maintained backwards compatibility with the way previous Munki clients handled certs and keys.

**Comment by pudquick** [comment]
Hi @FreshXOpenSource !

Weighing in on this one, because I'm knowledgable in a lot of the interactions between munki, the keychain, and the Security framework on macOS.

> We use a SCEP system via a mobileconfig profile

So unfortunately this is the part where the record makes a screeching scratch sound.

In my organization, we too use the SCEP profile - and I have a lot of issues with how Apple has implemented it!

The biggest problem I have with it is also the thing that makes it impossible for munki (and _lots_ of other projects) to utilize it: There is no ACL configuration item in the SCEP profile for whitelisting application access to the cert+keys that it installs in your keychain.

Let me break down how that impacts munki and how the pieces interact.

The SCEP profile performs an automatic process where it obtains (and renews) certs and private keys for macOS.

On macOS, certificates stored in the keychain do not have security controls on them (anyone can access them, even if the keychain is locked) - but private data, like **private keys** and passwords, do have ACLs / security control configurations which restrict access to the information to only approved applications (or whatever the security configuration is).

In this screenshot below, here's the Access Control list (ACL) set by macOS for a SCEP obtained private key (Keychain Access -> private key, File -> Get Info, Access Control tab:

<img width="534" alt="private_key" src="https://cloud.githubusercontent.com/assets/925910/18964182/99db055e-862c-11e6-8acd-cbea7b337144.png">

The applications in this list are the only things on your machine that can access the private key installed by a SCEP profile without triggering a GUI prompt. This list is set by Apple and is not adjustable by any configuration item in the SCEP profile.

When your certificate and private key renew, the new item will also obtain this default ACL and will not inherit any changes you made to the first one it obtained.

... but that's a moot point too, unfortunately, because there are _no automatable methods_ to change the ACL of a keychain item after it's already been created / added to a keychain. Even if you're root. This is an **intentional** security design choice by Apple.

There is a second hidden ACL which is the "allowed to make changes to the ACLs of this keychain item" which every keychain item has and the Keychain Access.app does not visually display. This list is always empty - which means, by default, **no application** on the OS has the right to make ACL changes to a keychain item.

As soon as an application attempts to adjust the ACLs of an already existing keychain item, if it's not in this (empty by default) "allowed to make changes to ACL" list, the Security framework of macOS forces a GUI-only interactive prompt to the end user. Command-line only tools will error out if they do not have access to a related graphical security context to make the GUI prompt appear.

Additionally, Apple released a security fix during 10.10 which disabled the ability to GUI automate Security prompt dialogs to deal with a virus that did exactly that:
https://blog.malwarebytes.com/cybercrime/2015/08/genieo-installer-tricks-keychain/

munki needs access to the private key when doing client certificates for secured repos because the key is used in conjunction with the client cert to encrypt the communication with the server (in addition to proving identity).

You can change the security of private keys at import time with the `security` command - so in theory, if you could export the cert and private keys from SCEP, you could re-import them with a better ACL ... but to export the private key, you have to be on the ACL for export ... and we're back where we started 😞

And again, even if your imaging/device setup solution is fine with an initial manual configuration step that would fix the permissions on the first cert+key that's received via SCEP - you'd have to do it again for every renewed one the SCEP profile installs.

Several of us in the Mac admin community have discussed this with Apple, but so far nothing has changed. As such, for now, SCEP profile installed certs+keys are not useful to the munki project, sadly. Sorry to be the bearer of bad news.

Your request could be considered for a statically imported cert+key - because whatever your setup process, you could configure the ACLs appropriately. But for SCEP, this will remain incompatible until changes come down from Apple.

**Comment by pudquick** [comment]
And actually - rethinking my last statement - at this point, munki wouldn't have to do anything to support statically imported cert+key.

It already uses the NSURLConnection/NSURLSession APIs which searches all available keychains (including the System keychain).

If you import a cert and key into System, configure the ACL to it so that munki (python) has rights to the key, and create the appropriate identity preference so that they're used for the URL of your munki repo, there's no need to provide on-disk certificates to munki or do any additional configuration other than telling munki where your repo is.

The APIs will automatically see and make use of the configuration to access the repo. As such, I'm going to close out this feature request.

**Comment by FreshXOpenSource** [comment]
Thanks @pudquick for this very enlightening explanation!

**Comment by oculos** [comment]
I also use Airwatch, and used Credentials to achieve the same goal. I got the CA on the keychain, as well as the certificate and the key. However, even after changing the ACL to allow everything, and creating the identity, it still doesn't work. Any clues why?

**Comment by MichalMMac** [comment]
Scep payload has `AllowAllAppsAccess`. Although not very secure it should grant acl access, right?

**Comment by oculos** [comment]
I didn't even managed to reach the munki repo after changing the acl manually.

**Comment by Sigma902** [comment]
Issue: AirWatch/Workspace ONE assigned applications not properly downloading
% sudo ./managedsoftwareupdate -v -v -v --checkonly
...
URLSession_task_didReceiveChallenge_completionHandler_
    Authentication challenge for Host: localhost Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
    Allowing OS to handle authentication request
    Download error -1202: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “localhost” which could put your confidential information at risk.
    SSL error detail: (-9813L, u'Cert chain not verified by root')
    ***Keychain list***
        "/Users/XXX/Library/Keychains/login.keychain-db"
    ***Default keychain info***
        "/Users/XXX/Library/Keychains/login.keychain-db"
    Headers: None
WARNING: Download of _AppName_ failed: (-1202, u'The certificate for this server is invalid. You might be connecting to a server that is pretending to be \u201clocalhost\u201d which could put your confidential information at risk.')
...
Resolved/Workaround: Find "localhost" self-signed root certificate in System keychain and mark Always Trust
