### ISSUE TITLE
Don't attempt to download icon where no icon hash present

### ISSUE THREAD

**Issue by keeleysam** [munki/munki#670]
Currently managedsoftwareupdate tries to download icons for all items, and caches them based on the icon hash in the pkginfo/catalog.

Since #444 makecatalogs generates these hashes automatically.

Munki shouldn't try to download icons when there is no hash, as if there is not one present and you're using a modern makecatalogs there almost certainly is not actually an icon to download and you generate a bunch of requests for items which always 404.

The question is, should this be a change in behavior or should it need yet another munki preference?

**Comment by erikng** [comment]
IIRC it only adds a hash if the icon isn't hard coded in the pkginfo. If you do something like this, it should respect both hash or icon path.

On Oct 5, 2016, at 2:30 AM, Samuel Keeley <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently managedsoftwareupdate tries to download icons for all items, and caches them based on the icon hash in the pkginfo/catalog.

Since #444<https://github.com/munki/munki/pull/444> makecatalogs generates these hashes automatically.

Munki shouldn't try to download icons when there is no hash, as if there is not one present and you're using a modern makecatalogs there almost certainly is not actually an icon to download and you generate a bunch of requests for items which always 404.

The question is, should this be a change in behavior or should it need yet another munki preference?

-

**Comment by gregneagle** [comment]
Closing this as no longer relevant with Munki 3.1.
