### ISSUE TITLE
Two options for limiting display of optional installs: hidden items or featured items

### ISSUE THREAD

**Issue by homebysix** [munki/munki#698]
When an organization has a long list of optional installs, the front page of Managed Software Center can become unreasonably long. As originally mentioned by @grahamgilbert in [this thread](https://groups.google.com/d/topic/munki-dev/oFhai8jdRz8/discussion) and discussed further in MacAdmins slack this morning, this could potentially be solved by:

- Hiding certain categories' products from the main page, using an array in the client preferences
- Adding a "Featured" section that shows the products that have `featured` set to `true` in their pkginfo

The second item appears to be in consideration for a future major release of Munki (https://github.com/munki/munki/issues/563), but I actually think the first item has its own merits as well. In my specific case, the ability to hide any products in the Printers category from the main page would _significantly_ clean up Managed Software Center.

In any case, I wanted to open this as a separate issue to encourage consideration of adding one or both of the above enhancements to Munki 2, rather than waiting for 3. Thanks for considering!

**Comment by erikng** [comment]
I wonder if you could do this with custom JavaScript.

On Feb 8, 2017, at 10:38 AM, Elliot Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


When an organization has a long list of optional installs, the front page of Managed Software Center can become unreasonably long. As originally mentioned by @grahamgilbert<https://github.com/grahamgilbert> in this thread<https://groups.google.com/d/topic/munki-dev/oFhai8jdRz8/discussion> and discussed further in MacAdmins slack this morning, this could potentially be solved by:

  *   Hiding certain categories from the main page, using an array in the client preferences
  *   Adding a "Featured" section that shows the products that have featured set to true in their pkginfo

The second item appears to be in consideration for a future major release of Munki (#563<https://github.com/munki/munki/issues/563>), but I actually think the first item has its own merits as well. In my specific case, the ability to hide any products in the Printers category from the main page would significantly clean up Managed Software Center.

In any case, I wanted to open this as a separate issue to encourage consideration of adding one or both of the above enhancements to Munki 2, rather than waiting for 3. Thanks for considering!

**Comment by homebysix** [comment]
To paraphrase:

> "I know, I'll use JavaScript."
> Now you have two problems.

;-)

**Comment by erikng** [comment]
Chances are you already have JavaScript in your client resources zip. :P

**Comment by gregneagle** [comment]
See https://github.com/munki/munki/wiki/Featured%20Items%20in%20Managed%20Software%20Center

**Comment by gregneagle** [comment]
(yes, I know it's for Munki 3, but I think Munki 3 will be shipping sooner than you might think.)

**Comment by gregneagle** [comment]
Closing this as it's addressed in Munki 3.
