### ISSUE TITLE
Munki 3.0.0.3086 crash at the end of run

### ISSUE THREAD

**Issue by MiqViq** [munki/munki#734]
managedsoftwareupdate -vvvv
...
    Skipping Apple Software Update check because sucatalog is unchanged, installed Apple packages are unchanged and we recently did a full check.
    CheckForSoftwareUpdates result: False
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1039, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 961, in main
    installinfo.save_pending_update_times()
  File "/usr/local/munki/munkilib/installinfo.py", line 155, in save_pending_update_times
    for name in pending_updates[category]:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 589, in enumeratorGenerator
    yield container_unwrap(anEnumerator.nextObject(), StopIteration)
objc.error: NSGenericException - *** Collection <__NSCFDictionary: 0x7fbd47783100> was mutated while being enumerated.

**Comment by MiqViq** [comment]
Munki 2.9.0.3039, no problems.

**Comment by rickheil** [comment]
I had the exact same traceback this morning - updating to latest (3170) I am not able to reproduce the issue yet.

**Comment by gregneagle** [comment]
You are reporting on an old build. The current build is 3.0.0.3187 and available as 3.0 Beta 1 here: https://github.com/munki/munki/releases/tag/v3.0.0b1

Your issue was almost certainly addressed 11 days ago here: https://github.com/munki/munki/commit/86fbd6299c1f4e496a0da6b3b354236a6f34f50d

If you can replicate the issue with the current build, please reopen this.
