### ISSUE TITLE
Munki 3.0.2 has version disrepancy

### ISSUE THREAD

**Issue by fseesink** [munki/munki#789]
This is a minor point but thought I'd mention it.  On this page:

https://github.com/munki/munki/releases/tag/v3.0.2

it indicates this is version **3.0.2.3348**.  However, once installed, the CLI tools report the version as **3.0.2.3347**.

This discrepancy, in turn, has such side effects as having apps like **AutoPkgr** reporting that "Munki tools 3.0.2.3348 update now available", but if you click the button to do so, it installs this version.  Since the version reported by the installed software is different than that listed in the .pkg file, you end up in an endless cycle.

![image](https://user-images.githubusercontent.com/48991/27936959-b35de6b8-6281-11e7-8253-5fd000cc8c12.png)

**Comment by gregneagle** [comment]
It's unfortunate that this causes problems for AutoPkgr but is consistent at least within the world of Munki.
The 3.0.2.3348 release contains these packages:

com.googlecode.munki.core: 3.0.2.3347
com.googlecode.munki.admin: 3.0.2.3347
com.googlecode.munki.app: 4.6.3348
com.googlecode.munki.launchd: 3.0.3265
com.googlecode.munki.app_usage: 3.0.2.3347

The "last-changed" thing was something in Managed Software Center, which bumped that version "last".  The command-line tools report the version within com.googlecode.munki.core.

It's conceivable there could be a release where there were a _lot_ of changes to the GUI apps and _no_ changes to the command-line tools, launchd files, or the app_usage package, resulting in something like:

com.googlecode.munki.core: 3.0.2.3347
com.googlecode.munki.admin: 3.0.2.3347
com.googlecode.munki.app: 4.6.3456
com.googlecode.munki.launchd: 3.0.3265
com.googlecode.munki.app_usage: 3.0.2.3347

and an overall Munki release of 3.0.2.3456.

Typically the command-line tools change the most and "fastest" so this is rarely a state we find ourselves in, but we're in that state with the 3.0.2 release.

I'm going to close this since there's really nothing here to address as far as Munki is concerned because it's operating as expected.
