### ISSUE TITLE
${problem_update_rows} ${problem_updates_header_message}

### ISSUE THREAD

**Issue by thomasm2film** [munki/munki#806]
After update to Munk 3.1, I get thes error on all macs:

${problem_update_rows} ${problem_updates_header_message}

![screen shot 2017-09-22 at 09 23 16](https://user-images.githubusercontent.com/10619297/30733633-054a6996-9f78-11e7-838c-9e9e69432e71.png)

**Comment by bochoven** [comment]
Does the issue persist when you close/reopen MSU?

**Comment by thomasm2film** [comment]
The issues is gone after re-launch of MSU. So only just after upgrade to 3.1.
Thanks

**Comment by gregneagle** [comment]
Yes, this happens if and only if Managed Software Center is open while Munki upgrades itself from pre 3.1 to 3.1. The html resources inside the app change, but the (old) running code doesn't know anything about the new html. Quitting and relaunching MSC.app causes the issue to disappear.

Machines that update to 3.1 in the background (via unattended_install) or at the loginwindow will not see/notice this issue.
