### ISSUE TITLE
gurl cannot resume from CloudFront (maybe other CDNs too) downloads

### ISSUE THREAD

**Issue by erikng** [munki/munki#817]
I'd like someone like @clburlison or @weswhet to confirm this, but I originally saw this behavior when writing the Imagr RAMDisk functionality, but chalked it up to the gurl being a fork.

In my testing yesterday of the MSC pending/problem updates issue, I realized that gurl wasn't resuming from CloudFront URL's, even though CloudFront supports resuming.

**Comment by grahamgilbert** [comment]
I am seeing this too. It presents itself as `kCFErrorDomainCFNetwork error 303`

**Comment by keeleysam** [comment]
What's the easiest way to consistently reproduce this behavior?  Disconnect and reconnect from a network in the middle of a large download?

**Comment by erikng** [comment]
Yeah. I do it in a VMware VM by just disconnecting the network, waiting for munki to fail and then turning it back on and running managedsoftwareupdate

**Comment by erikng** [comment]
https://gist.github.com/gregneagle/1816b650df8e3fbeb18f

Using this would be easier though.

**Comment by grahamgilbert** [comment]
I have not been able to reproduce this reliably with the script above. I'm leaning towards this being a cloudfront issue rather than a munki issue.

**Comment by clburlison** [comment]
I don't believe this actually is an issue with Gurl or Cloudfront but maybe how munki implements Gurl and resume downloads. Using the gurl test snippet from Erik with a Cloudfront URL I can resume downloads properly. However with the munki `fetch.munki_resource()` method I can 100% reliably get fetch to re-download the file from start on each run. 

(I'm using sudo python because I have middleware that needs to read a file limited to root)  
```python
cd /usr/local/munki
sudo /usr/bin/python
from munkilib import fetch
fetch.munki_resource('https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg', '/tmp/foo', message=None, resume=True)
```

Now during the run do a `Control + C` to cancel the download or turn off wifi. During the next run fetch will start the download without using the resume feature.

Best part is I can replicate this with google chrome and I know their CDN isn't Cloudfront.

I will keep poking to see what the root cause is but hopefully those steps help.
