### ISSUE TITLE
munki-notifier does not respect UseNotificationCenterDays if set in /var/root or managed preference.

### ISSUE THREAD

**Issue by weswhet** [munki/munki#819]
https://github.com/munki/munki/blob/7154507a229de30de60620a6ef32d2bf1b6aac4c/code/apps/munki-notifier/munki-notifier/AppDelegate.m#L117-L118

should be `CFPreferencesCopyAppValue`

**Comment by gregneagle** [comment]
Please see if this commit https://github.com/munki/munki/commit/42152f3ef737b3358024866ff154f2e7e8c1b42c addresses your issue.

**Comment by weswhet** [comment]
Does not appear to resolve the issue.

**Comment by gregneagle** [comment]
Are you up to adding some debug logging, building and testing to figure out why?

**Comment by weswhet** [comment]
yeah, It doesn't look like there are any logs for munki-notifier otherwise I would have posted them already. Unless i'm missing them somewhere. Happy to test/build.

**Comment by gregneagle** [comment]
There's aren't. You'd need to add NSLog() calls.

**Comment by gregneagle** [comment]
Oh, duh.
munki-notifier runs as the current GUI user. It can't read root preferences. The fix is still needed for managed preferences, though.

**Comment by gregneagle** [comment]
Nasty side-effect: a user could do `defaults write ManagedInstalls UseNotificationCenterDays -int 10000`, writing the pref to their own home dir, and now MSC will essentially never launch. Then they could also disable Notification Center notifications for MSC and then never ever be notified again.
So what's really needed is to use CFPreferencesAppValueIsForced --  if so, use the forced value returned by CFPreferencesCopyAppValue, otherwise use CFPreferencesCopyValue and target /Library/Preferences.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/commit/b59eeff1d17570f1383917c06129016f78a87f36 implements this strategy.

**Comment by gregneagle** [comment]
I'm closing this issue as fixed for Managed Preferences and can't fix/works as designed as far as root preferences.
