### ISSUE TITLE
ESC sends a "deny" when entering FileVault password

### ISSUE THREAD

**Issue by erikng** [munki/munki#834]
Today when performing an installation with a reboot (non forced), I decided to stop the installation and do something else first. Instinctively I hit the ESC key as that normally cancels a dialog box, but instead this sent a "deny". While this makes sense when thinking about how the dialog box was written, perhaps instead of immediately denying (which then requires the user to Auth upon reboot) we should put an "are you sure?" message and describe the behavior as to what will happen next.

During forced installs we may not want this to appear since it could be used as a way to bypass the installation.

**Comment by gregneagle** [comment]
This is standard Cocoa/AppKit dialog behavior: esc key doesn't cancel the dialog, it is the key equivalent of the non-default button (if there are two buttons), the "secondary" button if there are three.

I've never seen a password dialog that has Allow/Deny/Cancel; I don't think it's clear what a user with normal information would expect the difference to be between Deny and Cancel.  Maybe "Cancel logout" with esc mapped to that might make sense. I'd have to see how tricky that would be and how in line with Apple interface guidelines...

As for your workflow above:
You would have first been prompted to logout and restart: that would have been your opportunity to cancel. Once you've decided to log out, you then can allow or deny Munki the use of your password to do an auth restart. The wording of the dialog seems clear to me.

I'd rather _not_ bother the user with an "Are you sure?" dialog since the consequences aren't terrible: it's not like it leads to data loss.
Perhaps esc should have no effect in this dialog and users have to click "Deny". Again, I'd have to see how much work it is to _not_ use the Apple default behavior here. (I'm not explicitly wiring up either Return _or_ esc)

**Comment by erikng** [comment]
Perhaps that's the main issue then. When I hit ESC, I had no option to not logout. It happened as soon as I hit ESC and then the loginwindow appeared, followed by MunkiStatus.

**Comment by gregneagle** [comment]
The normal/expected sequence of events:

1) Managed Software Center displays some available updates, one or more requiring a restart.
2) You click "Update all"
3) A dialog informing you that you need to logout to install updates and restart is displayed with choices "Log out and update" and "Cancel". Presumably you clicked "Log out and update".
4) If FileVault is enabled and all the other prerequisites are satisfied, another dialog is displayed asking to allow or deny the use of your password for an _authenticated_ restart. At that point you've already agreed to log out. Nothing in the dialog is designed to stop logout at this point. You hit the esc key or its Touch Bar doppelgänger, and told MSC you declined to provide a password (since that is the keyboard equivalent of clicking "Deny" in this context).

Is that an accurate reconstruction of the sequence of events you experienced? If so, given that sequence, re-read my first comment/reply and see if anything there makes sense, or if we should leave things as they are.

**Comment by erikng** [comment]
Yes this sounds accurate and makes sense. In essence I had already "approved" the behavior twice. My memory is failing me, but I will test this in a VM next week and see what happens. If the four events you detailed happened, I will close this ticket.

**Comment by gregneagle** [comment]
I'm going to close this still this is not really a code issue; it behaves as expected/designed. If you revisit this and would like to propose a change in behavior you can re-open this or create a new issue proposing your change in behavior.
