### ISSUE TITLE
[FR] Mark pkgs for pre-caching

### ISSUE THREAD

**Issue by nathanperkins** [munki/munki#873]
It'd be a cool feature if we could mark packages for pre-caching, so that they can be installed without munki server connection via on-demand or when enforced by a force_install_after_date.

This would be helpful for us, as our Munki server is internal network only so the on-demand items will fail outside our network.

**Comment by gregneagle** [comment]
You'll find a test implementation in the Munki3dev branch: https://github.com/munki/munki/tree/Munki3dev

And pre-built packages here: https://munkibuilds.org/_branches/Munki3dev/

And discussion here: https://groups.google.com/d/topic/munki-dev/UOoN6gqi6zA/discussion

Pay specific attention to: https://groups.google.com/d/msg/munki-dev/UOoN6gqi6zA/SIyeYb1ICAAJ

But precaching alone may not be enough for a use-case of "so that they can be installed without munki server connection via on-demand".

Items marked for "force_install_after_date" _are_ downloaded by the time users receive notifications (as are all pending managed installs).

**Comment by nathanperkins** [comment]
Honestly, most of my use-case thought was for "force_install_after_date" so if that's already in, I can probably handle my other use-case

**Comment by nathanperkins** [comment]
Sorry, accidentally clicked the close and comment.

Most of my thought was for "force_install_after_date" so if that is already implemented you can probably just close this.

The other use-case for on-demand pkgs without internet can probably be handled by manually caching a pkg as a file and running another nopkg script to install it on-demand, if #872 is implemented.

**Comment by gregneagle** [comment]
Items are not presented to users as pending installs until after they've been successfully downloaded to /Library/Managed Installs/Cache. This includes, but is not limited to, items marked with `force_install_after_date`: _all_ pending updates are cached in /Library/Managed Installs/Cache
