### ISSUE TITLE
MSC 5.1.0.3665 doesn't load icons

### ISSUE THREAD

**Issue by asemak** [munki/munki#881]
Open MSC with an earlier version of Munki installed and see items with icons

Close MSC

Install MSC 5.1.3665

Open and MSC and confirm no icons are loaded

**Comment by gregneagle** [comment]
I’m definitely not seeing this behavior.

**Comment by asemak** [comment]
To clarify, MSC does load icons but only the generic macOS pkg icon, no custom icons.

I'm seeing the same behaviour on multiple machines and both Mojave 10.14.2 and 10.13.6.

kevinmcox is also seeing similar behaviour as shown in his video on Slack

**Comment by gregneagle** [comment]
And yet it works as expected for me.
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/700560/49529071-1d80c400-f86a-11e8-832d-acd629add5cb.png">

**Comment by gregneagle** [comment]
So we need to determine what about your (and Kevin's) icon's the MSC.app doesn't like.

**Comment by davidmnelson** [comment]
I'm seeing this with 5.1.0.3665 (3665) on 10.14.1 and 10.12.6.

Some icons are missing while a handful are present. On both systems I've tested, the same icons are either present or missing.

I tried trashing "/Library/Managed Installs/icons" and checking for updates. All icons are cached but the same ones as before are missing.

![msc missing icons](https://user-images.githubusercontent.com/4750692/49529178-591b8e00-f86a-11e8-879a-e316ea07fee8.png)

**Comment by gregneagle** [comment]
Looks like the ones displayed are for installed applications. MSC (since forever) will attempt to grab icons from installed applications if there aren't any it can use in /Library/Managed Installs/icons.

So why doesn't MSC.app like the icons in /Library/Managed Installs/icons on your machines, but is happy with them on mine?

**Comment by gregneagle** [comment]
Here's the relevant code (I think): https://github.com/munki/munki/blob/Munki3dev/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/MunkiItems.swift#L215-L245

**Comment by davidmnelson** [comment]
I've been spot checking a bunch of items that load an icon vs one that don't. It looks like the ones that fail to load an icon are the ones that have a icon_name key. The ones that do load an icon do not have filename specified and are divining the icon's filename from name of the package.

**Comment by gregneagle** [comment]
...and now I see the bug. `(icon_name as NSString).pathExtension` would return "jpg" or "gif" or "png" and not ".jpg" or ".gif" or ".png"... Credit translating from Python to Swift and the subtle differences in mostly-equivalent functions. Didn't hit me probably because all my icons are png and I don't explicitly set the icon_name key so the icons names are constructed from the value of the "name" key + ".png"

**Comment by kevinmcox** [comment]
Nice catch @davidmnelson, looks like that is the reason I'm seeing some but not all as well.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/e7eaf4fe0a7f78d97538221846dafa570754bd72

**Comment by gregneagle** [comment]
`code/tools/make_munki_mpkg_from_git.sh -b Munki3dev` under Xcode 9.4.1 should build a new pkg if you want to test; otherwise please test when DP2 is released and reopen this if it's still broken.

**Comment by davidmnelson** [comment]
I just built and installed 5.1.0.3667 (3667) and the icons are all loading again. Thanks!
