### ISSUE TITLE
${category_list} is not being built correctly for MSC 5.1

### ISSUE THREAD

**Issue by kevinmcox** [munki/munki#882]
Per the discussion on Slack:

`${category_list}` is not being built correctly when used in a custom sidebar.

Links generated are missing `munki://`.

e.g. 
`<a href="category-Audio.html">Audio</a>`
instead of
`<a href="munki://category-Audio.html">Audio</a>`

**Comment by gregneagle** [comment]
Should be addressed here:
https://github.com/munki/munki/commit/9d8cb68b8367fa8a535b1e5391db39a7af3e1c04

`code/tools/make_munki_mpkg_from_git.sh -b Munki3dev` under Xcode 9.4.1 should build a new pkg if you want to test; otherwise please test when DP2 is released and reopen this if it's still broken.

**Comment by kevinmcox** [comment]
Thanks Greg.
