### ISSUE TITLE
Optional installs for higher OS versions not shown in red in MSC 5.1.0.3720 updates tab

### ISSUE THREAD

**Issue by dhmoore** [munki/munki#914]
I set ShowOptionalInstallsForHigherOSVersions to true. In macOS 10.13 and 10.14 (at least), when an item that needs an OS update is shown in Managed Software Center 4.8.3628, the text "An older version is currently installed..." is displayed in red (as expected). In Managed Software Center 5.1.0.3720, the text "An older version is currently installed..." is displayed in black. This only affects the Updates tab. The Software tab shows "Update available" in red, and the item detail page shows "An older version..." in red in both versions of Managed Software Center. 

The html generated by munkitools 3.5.3.3640 and 3.6.0.3721 is identical.

There's also a difference in the number of blank lines displayed before the description in the updates tab.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/commit/13b0b840f24c81c415418f912fe4d174d815fb69 addresses the text color issue. Since I don't remember why I was originally filtering out span tags here, I worry that this change will trigger a different issue. We'll have to wait and see, I guess.

I also see the "difference in the number of blank lines displayed before the description in the updates tab" you mention, but in my one test, I preferred the MSC 5.x behavior.

**Comment by dhmoore** [comment]
RC5 with the above fix resolves the issue. I like the MSC 5.x blank line behavior better, too.
