### ISSUE TITLE
Feature Request - Do not run when tethered

### ISSUE THREAD

**Issue by miawri** [munki/munki#942]
Feature Request: -

It would be great if we had a boolean ManagedInstalls key similar to `RunWhenTethered`that would check whether the primary IP address started with 172.20.10. and munki would not run if the plist was set to `False`.

This would save having to rewrite any sal / munkireport preflight scripts as munki itself would be dealing with scenario.

**Comment by gregneagle** [comment]
There's nothing at all magical or "tethered" about an IP address starting with 172.20.10. so as proposed, I don't see this idea getting any traction.

This type of thing is almost always organization and implementation-dependent, and that's why it's traditionally been left to Munki preflight scripts.

**Comment by natewalck** [comment]
I think dealing with this in a preflight is the right way to go. 

Also do *all* tethered devices use that IP range or does it vary from device to device? (Say iOS vs Android)

Nate
