### ISSUE TITLE
AVG is identifying a couple munki python scripts as a threat.

### ISSUE THREAD

**Issue by normhayes** [munki/munki#943]
<img width="993" alt="Screen Shot 2019-07-16 at 1 40 14 PM" src="https://user-images.githubusercontent.com/307030/61399056-2fa3f580-a882-11e9-9e0d-1b2cf9191203.png">
This has been happening for a bout a week now.
![Screen Shot 2019-07-17 at 11 10 28 AM](https://user-images.githubusercontent.com/307030/61399970-19973480-a884-11e9-961e-e774c871a726.png)
 I've added them as Exceptions, but it still wants to resolve these so called threats.

**Comment by gregneagle** [comment]
This is not a support forum. Consider posting on munki-discuss as suggested when creating a new issue.

**Comment by normhayes** [comment]
I'm not sure I understand. I'm not asking for support. I thought I was reporting a problem with the software.

**Comment by gregneagle** [comment]
The problem is as likely to be with AVG, and one of the two files you flag isn't even part of Munki. The discussion has commenced in munki-discuss, so let's see where it goes.

(There are far more people who watch and participate in munki-discuss than pay attention to issues here (which is generally just me), and you are far more likely to connect with someone else who uses AVG. This is why I ask that these Issues be reserved for reproducible, actionable code issues. It might turn out that this will eventually be the case for this, but that's not clear yet.)

**Comment by normhayes** [comment]
Okay, thank you for your help.
