### ISSUE TITLE
Inclusion of certifi python package to allow for SSL root cert verification

### ISSUE THREAD

**Issue by sphen13** [munki/munki#958]
I came across an issue while updating my b2 middleware to be compatible with the embedded python3 binary. This middleware requires a few https/api requests to be made for authentication. It would seem that urllib's SSL verification failed when using embedded python as there are no root certs installed in munki's python version. For now I am packaging a pem file and referencing that within the middleware, but allowing python to natively check root certs would be best.

The [certifi](https://pypi.org/project/certifi/) package if included could possible solve this for myself and any other middleware that may require https calls via urllib.

Thank you.

**Comment by gregneagle** [comment]
At this time I want to be very slow, careful, and deliberate about what additional Python modules I include with Munki, since then I'll be on the hook for making sure they are kept updated if there are security implications, or in the case of certifi, if the certs are updated. Since I'm not currently using certifi, I'd likely miss any issues until someone else brought them to my attention.

Is there an obstacle to you being able to add this yourself for your deployment?

**Comment by sphen13** [comment]
I hear you on this. Thank you.

Not exactly sure how I would load a module into the relocated framework - but honestly as i think about this I may try to rewrite the middleware to use the same gurl module that munki uses.

**Comment by gregneagle** [comment]
`/usr/local/munki/Python.framework/Versions/Current/bin/python3 -m pip install certifi`

**Comment by sphen13** [comment]
Well then why don’t you just do it for me? ;) thank you. I have good options. Thanks for spelling it out.

**Comment by gregneagle** [comment]
(and then guessing you could package up /usr/local/munki/Python.framework/Versions/Current/lib/python3.7/site-packages/certifi for mass deployment)
