### ISSUE TITLE
managedsoftwareupdate fails to run after upgrade to 4.0.1

### ISSUE THREAD

**Issue by DarthUndesirable** [munki/munki#979]
After upgrading to Munki 4, `managedsoftwareupdate `keeps failing. I can reinstall Munki 3 and it works but once I upgrade, it breaks. I referenced issue #963 but it seems the problem persists.

```
Managed Software Update Tool
Copyright 2010-2020 The Munki Project
https://github.com/munki/munki

Starting...
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1141, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 862, in main
    client_id=unicode_or_str(options.id))
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 64, in check
    dummy_keychain_obj = keychain.MunkiKeychain()
  File "/usr/local/munki/munkilib/keychain.py", line 559, in __init__
    add_ca_certs_to_system_keychain()
  File "/usr/local/munki/munkilib/keychain.py", line 179, in add_ca_certs_to_system_keychain
    'No CA cert info provided, so nothing to add to System keychain.')
  File "/usr/local/munki/munkilib/display.py", line 203, in display_debug2
    if int(prefs.pref('LoggingLevel')) > 2:
ValueError: invalid literal for int() with base 10: ''
```

macOS 10.15.3
managedsoftwareupdate 4.0.1.3899

**Comment by gregneagle** [comment]
It's almost certainly related to this issue as you guessed. https://github.com/munki/munki/issues/963

You have set your LoggingLevel to an empty string. Don't do that.

**Comment by gregneagle** [comment]
(Set it to an _integer_)

**Comment by gregneagle** [comment]
Addressed here https://github.com/munki/munki/commit/f57336eb3cf216a5daa2181d3678963c4da623be for future admins that make a similar mistake.

**Comment by blackthroat** [comment]
I know this issue is closed, but just in case anyone else is running to this issue and their profiles have been working seemingly fine up until upgrading to munkitools 4.0.1, I'll share my experience.

I created the following .mobileconfig file through Profile Manager on a machine running 10.13.6

![image](https://user-images.githubusercontent.com/25038086/74279920-668b9e00-4ce1-11ea-843a-9f9957281895.png)

Upon examining the .mobileconfig file, it shows those values as empty strings instead of integers:

![image](https://user-images.githubusercontent.com/25038086/74279955-730ff680-4ce1-11ea-88ce-6805b88b1ff9.png)

I also confirmed on the end-user's machine those values are not set correctly through Profiles:

![image](https://user-images.githubusercontent.com/25038086/74280625-840d3780-4ce2-11ea-8991-30ea34845bf3.png)

I then installed ProfileCreator (https://github.com/ProfileCreator/ProfileCreator), imported the same .mobileconfig file created by Profile Manager, tried to export and got this message:

![image](https://user-images.githubusercontent.com/25038086/74280085-abafd000-4ce1-11ea-8b1f-b892ef923640.png)

When I cleared out and re-entered the numbers, exported a new .mobileconfig file, the values then populated correctly as integers. 

Might be a bug with Profile Manager or maybe just isolated to my machine.

**Comment by DarthUndesirable** [comment]
@blackthroat Thanks for this input. It's not exclusive to your machine and may be a bug. That's the exact experience I was having with Profile Manager. I created the profile and the string was empty after installing the profile, even though I had initially specified an integer when it was created. After creating the .mobileconfig a second time, the values populated successfully.
