### ISSUE TITLE
managedsoftwareupdate is deriving incorrect package version number

### ISSUE THREAD

**Issue by mtconleyuk** [munki/munki#990]
(managedsoftwarecenter version 4.1.4.3949)

- Created a package named **BlockSecurityUpdate2020-002-1.0.pkg**.
- Installed into repository using makecatalog.
- Verified that both **BlockSecurityUpdate2020-002-1.0.pkg** and **BlockSecurityUpdate2020-002-1.0.plist** are present where they should be.
- Run managedsoftwareupdate via Managed Software Centre app.
- Get an error reporting that the pkginfo could not be found. Log report:-

```
May 11 2020 10:44:38 -0400 DEBUG1: * Processing manifest item BlockSecurityUpdate2020-002 for install
May 11 2020 10:44:38 -0400 DEBUG1: Looking for detail for: BlockSecurityUpdate2020, version 002...
May 11 2020 10:44:38 -0400 DEBUG1: Not found
May 11 2020 10:44:38 -0400 WARNING: Could not process item BlockSecurityUpdate2020-002 for install. No pkginfo found in catalogs: production
```

- From the log, it appears that managedsoftwareupdate is not scanning for the first hyphen from the right, as it should, as it thinks the version number is '002' rather than '1.0'.
- Deleted the problematic package, replaced it with a new one named **BlockSecurityUpdate2020002-1.0.pkg**, and everything works as expected.

**Comment by gregneagle** [comment]
The name of the _package_ is unimportant here.
What is value for "name" in the pkginfo? If it's "BlockSecurityUpdate2020-002", then you are encountering known behavior.
See: https://github.com/munki/munki/wiki/FAQ#q-i-keep-seeing-warnings-like-warning-could-not-process-item-office2011_update-1442-for-update-no-pkginfo-found-in-catalogs-production-yet-there-is-definitely-an-item-named-office2011_update-1442-in-the-production-catalog-what-is-happening
and: https://github.com/munki/munki/wiki/Manifests#item-names

Munki can't distinguish between an item named "BlockSecurityUpdate2020", version "002-1.0" and one named "BlockSecurityUpdate2020-002", version "1.0", since both could be represented in a manifest (or in other contexts) as "BlockSecurityUpdate2020-002-1.0" 

Rename the item "BlockSecurityUpdate2020_002" and the issue will go away.
