### ISSUE TITLE
sug: install symlinked python as munki-python

### ISSUE THREAD

**Issue by davvid** [munki/munki#996]
With munki installed, it is possible to get this result because `/usr/local/munki` is listed in `/etc/paths.d/munki`:

```
$ which python
/usr/local/munki/python
```

Most user may not notice, but this would be possible to remedy by renaming the symlink to `munki-python` and adjusting the scripts accordingly.

A naive `git grep /usr/local/munki/python` in the repo finds 19 occurrences, so this seems like it would be straightforward to change.

Since this looks really quick to fix, I'll put together a PR for review.  Thanks for Munki!

**Comment by gregneagle** [comment]
I'd argue this is _not_ common, as it's highly unusual to not have `/usr/bin` earlier in your PATH than `/usr/local/munki`, but it _is_ possible. Apple currently ships Python available at `/usr/bin/python`.

Of more concern is what happens if Apple no longer ships Python at `/usr/bin/python`, as they've been warning they will "in a future version of macOS"; it's then even more likely that people will use Munki's Python unawares.

So I think this is probably a good change.

It is a _breaking_ change, however, for those admins who ship their own Python and use a symlink at `/usr/local/munki/python` to point to their Python. So I've pointed the PR against Munki5dev instead of main, and we'll target this for the Munki 5.1 release. I'll post a warning/request for feedback in the munki-dev Google Group.

**Comment by erikng** [comment]
This is a great change and something I too discovered this week but forgot to say anything.

**Comment by grahampugh** [comment]
I have no problem with the change, but just to say, I would be surprised if /usr/bin/python was removed - more likely it will be a stub that invokes the pop up installer for the Xcode CLI tools, as with git, java, python3 etc.

**Comment by gregneagle** [comment]
Change was merged to the Munki5dev branch and will be part of the Munki 5.1 release.
